### ISSUE TITLE
Gutter symbols don't appear at runtime

### ISSUE THREAD

**Issue by Bulmanator** [x13pixels/remedybg-issues#100]
The breakpoint symbol will disappear at runtime and then doesn't come back meaning you can place the same breakpoint twice. Upon running again however, it will collapse the duplicate breakpoints into one.
Here is an example of me placing the same breakpoint twice:
![bug](https://user-images.githubusercontent.com/8584482/56454686-bd884700-634c-11e9-8a5f-64ed1a233539.png)
It also doesn't show the yellow arrow signifying a breakpoint has been hit/ which line the debugger is up to. The example below has hit a breakpoint on line 5:
![break](https://user-images.githubusercontent.com/8584482/56454740-59b24e00-634d-11e9-85ac-15dd6d90c15e.png)

**Comment by x13pixels** [comment]
This appears to be another difference between the Visual Studio compiler and Clang wrt to PDB generation. This has been nominally fixed.
