### ISSUE TITLE
Strange crashes during recompiles

### ISSUE THREAD

**Issue by cmuratori** [x13pixels/remedybg-issues#101]
When recompiling the target executable on Handmade Hero, we got a lot of Remedy crashes with 0.2.2.  Not sure why these are happening, but you can see them on Day 526's videos.  We of course couldn't report minidumps because Visual Studio has crapped the bed, but I will try to get WinDBG set up as a just-in-time debugger so we can capture minidumps from now on.

The minidump _does_ seem to have been reported to Microsoft, so if you register with them and try to get the crash reports, that may also have it (not sure).

\- Casey

**Comment by x13pixels** [comment]
(0.2.2.1) Fixed crash in handling of file checksums introduced in 0.2.2.0.
