### ISSUE TITLE
Everything in watch window results in "identifier <name> not found"

### ISSUE THREAD

**Issue by Bulmanator** [x13pixels/remedybg-issues#104]
Every time I put an expression into the watch window it doesn't display anything about the variable and instead just states that the "identifier <name> not found" where <name> is the variable name. On the modules tab, it shows the .exe I am currently running with the correct path to the .pdb file and states that the symbols have been loaded.
I am compiling with clang++.exe 8.0.0 and with --driver-mode=cl to output .pdb files with the /Zi flag.

**Comment by x13pixels** [comment]
Following is the difference between the PDBs from the VS compiler and Clang: VS emits S_REGREL32 for local variables (values are stored relative to a register, usually RSP) whereas clang emits S_LOCAL and S_DEFRANGE_FRAMEPOINTER_REL pairs, instead.

The task, here, would be to add support for local variables specified by S_LOCAL/S_DEFRANGE_FRAMEPOINTER_REL.

**Comment by ghost** [comment]
If I understand this correctly, does that mean RemedyBG does not currently support debugging Clang executables?

**Comment by x13pixels** [comment]
@EmGustave This is correct. Lookup of local variables does not currently work for Clang generated executables.

**Comment by x13pixels** [comment]
[2.8.1] Added better handling of Clang generated PDBs for watching local variables.
