### ISSUE TITLE
XMM registers broken?

### ISSUE THREAD

**Issue by cmuratori** [x13pixels/remedybg-issues#110]
Currently, there seem to be two problems with XMM registers (and perhaps Y and Z, but I haven't tested):

1) In the Registers window, the top 32 bits of each 64-bit half of the register display always shows 0 no matter what is actually in the register, and

2) Although you can type rax/rcx/etc. into the watch window to see the contents of that register, you cannot type xmm0/xmm1/etc. into the watch window.

\- Casey

**Comment by x13pixels** [comment]
Fixed formatting of XMM/YMM/ZMM registers.

**Comment by x13pixels** [comment]
Can now specify xmm0-15, ymm0-15, and zmm0-15 registers in watch window.
