### ISSUE TITLE
Stepping type should be stateful

### ISSUE THREAD

**Issue by cmuratori** [x13pixels/remedybg-issues#112]
At the moment, it is kind of hard to use disassembly window stepping, because if you move up to the watch window to enter a value, you have to remember to re-select the disassembly window before stepping again or it will think you want to step a line of source code, even though you haven't ever clicked back on a source window.

I would recommend that the stepping type should be stateful (and perhaps even have an indicator).  If you click on a disassembly view, the state changes to disassembly stepping.  If you click on a source view, it changes to source stepping.  Clicking on any other window doesn't change it.  That way, it will generally have the "least surprise" for someone using it, since it will always step the same way it was when last they focused on a code display.

\- Casey

**Comment by x13pixels** [comment]
Stepping type (line vs. instruction) is now stateful based on the _last_ type of window that had focus (text or disassembly) and not whether the disassembly window _currently_ has focus. Clicking on another pane (e.g., the watch window) no longer resets the state back to line-based stepping.
