### ISSUE TITLE
Thread names in Thread window

### ISSUE THREAD

**Issue by direbroom** [x13pixels/remedybg-issues#114]
The threads (other than "Main Thread") don't seem to have names in the thread window.
AFAIK there are 2 ways to set the thread name:
 - throwing exception 0x406D1388 with a bunch of parameters
 - (on newer win versions) there's SetThreadDescription

**Comment by x13pixels** [comment]
[0.3.8.0] Added support for both exception based and SetThreadDescription mechanisms for naming threads.
