### ISSUE TITLE
Output window doesn't refresh when other window is focused

### ISSUE THREAD

**Issue by KayVerbruggen** [x13pixels/remedybg-issues#115]
If I have the window of my program open, the output window doesn't refresh until I tab back to the  debugger. I know that it doesn't refresh for performance reasons, but maybe the output window should be an exception (if possible). If it can't be changed per window, maybe an option to just refresh all the time would be fine as well. It's just way easier to check for output and have the window open simultaneously, I hope this gets considered.

**Comment by x13pixels** [comment]
We now force a redraw whenever the output window is updated. Fixed in 0.2.7.1.
