### ISSUE TITLE
Go to line

### ISSUE THREAD

**Issue by sonictk** [x13pixels/remedybg-issues#117]
Not sure if this feature is already implemented, but for source files that are thousands of lines long, navigating to the right line in order to set a breakpoint is sometimes too arduous a task that has me switching back to VS or WinDbg to do the debugging instead.

It would be nice to have a basic navigate-to-line feature for these sorts of situations.

**Comment by x13pixels** [comment]
Related to #33 (Search functionality in all/source/disasm/watch windows).

**Comment by x13pixels** [comment]
[0.2.8.1] Added "Go To Line", initiated with Ctrl+G, for text windows.
