### ISSUE TITLE
Allow for filtering process list in Attach to Process window

### ISSUE THREAD

**Issue by sonictk** [x13pixels/remedybg-issues#119]
Currently, I cannot seem to find a way to filter the process list in the attach to process window, or displaying additional information about each process other than its PID. 

It would be helpful to see the full command line string associated with each process, along with being able to quickly type in a filter text field to find the process to attach to easily. This is especially useful when you have several instances of the same application open and you're attempting to debug just one of them.

**Comment by x13pixels** [comment]
@LordJoNil: "When in the Attach to Process window it would be nice if when pressing a letter key the first process that begins with that name would be select. 

so for example if i have multiple processes called firefox.exe and press the f key the first Firefox process would be selected. And if i continue pressing f i could cycle among the processes that begin with the letter f. "

**Comment by jockus** [comment]
I'd suggest also adding a filter textbox that does substring matching.

**Comment by sonictk** [comment]
@x13pixels I see that you added this in the latest `0.3.3.0` release; thank you _so much_. This makes _such_ a huge difference (along with conditional breakpoints you added a while ago) when I'm using remedybg for debugging.
