### ISSUE TITLE
LowLevelKeyboardHook lag on keyboard input

### ISSUE THREAD

**Issue by Zilarrezko** [x13pixels/remedybg-issues#121]
When a user sets a low level keyboard hook via 
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ms644985(v=vs.85)
and
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowshookexa

once the hook is in place RemedyBG and Visual Studio both lag on each keypress such as f10 or typing in the watch window or any other input box of course.
Of course, going into control and using the step of choice will not produce lag.

**Comment by Zilarrezko** [comment]
I've been told that there might not be anything that can be done for the lag. I will still defer to you if it can or cannot and if not then obviously close.

**Comment by x13pixels** [comment]
Will take a look and see if there is anything we can do.

**Comment by x13pixels** [comment]
Like you said it doesn't look there is anything I can do on my end for this one.
