### ISSUE TITLE
Keep instruction pointer in the middle of window during stepping.

### ISSUE THREAD

**Issue by LowySt** [x13pixels/remedybg-issues#122]
Especially when debugging assembly — where you need to step a lot of code — not seeing what the next couple of instructions are because the current line is at the bottom of the window is problematic, and having to often scroll is annoying.

Maybe it could be a configurable option?

**Comment by x13pixels** [comment]
[0.2.8.1] Disassembly will now auto-scroll to center when nearing the bottom.

Leaving this open, though, as I could still see adding an option for locking the current position to the center of the view.

**Comment by x13pixels** [comment]
0.3.9.9 adds an option to the disassembly context menu, "Keep Location Centered".
