### ISSUE TITLE
Unable to open files in subst drive

### ISSUE THREAD

**Issue by Zilarrezko** [x13pixels/remedybg-issues#126]
I seem to be unable to go see a subst drive when opening, as well as when debugging, if I compiled with cl from the commandline while within a subst drive, remedybg cannot find the file.

**Comment by Zilarrezko** [comment]
I suspect it works somewhat as thus.
I have my command prompt in the subst drive (W for example, subst from D:\workspace\), I compile using cl, it generates a PDB and remedybg is unable to open/find the source files.

It seems only when I have the commandline with a cwd not based on the substed drive (D:\workspace\ instead of W:\) am I able to compile it and remedybg is able to find the source files.

**Comment by x13pixels** [comment]
The Output window in RemedyBG will contain a message in the case the file cannot be opened. Can we take a look and see what file it is trying to open?

**Comment by Zilarrezko** [comment]
![image](https://user-images.githubusercontent.com/8561784/64304668-8e602400-cf41-11e9-971c-9cecd3f600fe.png)

**Comment by Zilarrezko** [comment]
I would also like to add that in ctrl-o Remedybg seems unable to see subst drives (if it is unclear, this is 0.2.8.2)

**Comment by x13pixels** [comment]
If RemedyBG is unable to open the file but it exists on disk then either i) RemedyBG was launched with elevated privileges or ii) the drive was substituted from a command-prompt launched with elevated privileges. Could this be the problem?

**Comment by Zilarrezko** [comment]
Yes, I need RemedyBG to have elevated privileges to start a program that needs to be started with elevated privileges. The first is this specific case.

**Comment by x13pixels** [comment]
Okay. In that case you will want to create the substituted drive with elevated privileges as well (from a command-prompt with elevated privileges, for instance). Otherwise, RemedyBG, or any application launched with elevated privileges, will not be able to see the substituted drive.

**Comment by Zilarrezko** [comment]
Can I ask the solution to the second if you know?

**Comment by Zilarrezko** [comment]
Also yes, your solution is a solution for me. I had no idea how finicky subst and different privileges were. It seems I will need the subst script to be elevated, the command prompt that I used to compile needs to be elevated to see the subst drive even. Thanks for your help.

I'm inferring there is no programmatic way on your end to remedy this? If so, I'll defer to you to close the issue.

**Comment by x13pixels** [comment]
There is nothing an individual application can do about this. Closing.
