### ISSUE TITLE
Watch Window Input Crash

### ISSUE THREAD

**Issue by AndrewNRe** [x13pixels/remedybg-issues#128]
![RemBug](https://user-images.githubusercontent.com/53196429/65394413-12d8e200-dd4b-11e9-90e3-2abff5f0c41c.JPG)
While I was debugging, I wanted to move a pointer from the 6th or 7th watch window slot (I forgot) to the slot below it with the other pointer to subtract the two addresses.
However, as soon as I pressed CTRL X after highlighting the pointer I wanted to move and clicked on the slot I wanted to move it to. Remedy crashed.

**Comment by x13pixels** [comment]
Fixes watch window input crash when a watch expression is deleted while in the middle of watch expression render loop.
