### ISSUE TITLE
Tabs are too easy to close by accident

### ISSUE THREAD

**Issue by pgalkin** [x13pixels/remedybg-issues#132]
![image](https://user-images.githubusercontent.com/7285838/65886084-1e648280-e3b5-11e9-9f06-fbd6e3780f77.png)

They are too small. I often close Watch window when I didn't mean to. I think they should be a bit wider by default, especially if there is plenty of room.

**Comment by x13pixels** [comment]
Fixed for 0.3.0.6.

Removed close button from individual tabs. The 'x' button on the right-hand side of the toolbar still remains. Also, for text windows added "Close" to tab's context menu items.
