### ISSUE TITLE
Thread local variables?

### ISSUE THREAD

**Issue by Rageoholic** [x13pixels/remedybg-issues#133]
Hi. I was just wondering if there were any plans to add support for thread local variables in the watch window. I'm trying to use them in a specific place and while I can make them work out sort of it would be nice to just be able to look at the watch window rather than doing sprintf OutputDebugStringA stuff y'know

**Comment by x13pixels** [comment]
[0.3.5.0] Added support for implicit global and static local thread local storage variables.

**Comment by Feacur** [comment]
Heya, @x13pixels! Evidently, there's some divergence between MSVC's and Clang's static variables. That's not a bug at your side, however! Clang prefixes such variables with their scope name or something (I'm not entirely sure if this is solvable with compiler/linker flags or something)

# MSVC #
![image](https://user-images.githubusercontent.com/1132582/114948153-254bcc80-9e57-11eb-9426-c3a8741f4aa7.png)
... and its PDB
![image](https://user-images.githubusercontent.com/1132582/114949093-f8001e00-9e58-11eb-86bd-b75c57f05f6c.png)

# Clang #
![image](https://user-images.githubusercontent.com/1132582/114948290-5e843c80-9e57-11eb-90d2-560cf3065a88.png)
...
![image](https://user-images.githubusercontent.com/1132582/114948630-10bc0400-9e58-11eb-8bf7-9e0edb05015e.png)
... and its PDB
![image](https://user-images.githubusercontent.com/1132582/114948707-38ab6780-9e58-11eb-9966-01969911d95c.png)

P.S.: thank you for the awesome debugger, it works like a charm and convenient UX-wise =)
