### ISSUE TITLE
Allow for showing ASCII characters in Memory window

### ISSUE THREAD

**Issue by sonictk** [x13pixels/remedybg-issues#134]
It would be useful, when inspecting long strings or searching for strings in a data structure, to be able to see a corresponding column for characters in the memory window, similar to how hex viewers would usually have it as a separate column.

**Comment by Zilarrezko** [comment]
I thought this was already a thing. If you right click in the watch window and set the cols to a lower number so that it's not off the screen, is this what you're thinking of. Or were you thinking of something else?

**Comment by x13pixels** [comment]
Right-click on the memory window and choose "Show Ascii".
