### ISSUE TITLE
Allow for easy way to get variables from Watch window to Memory window

### ISSUE THREAD

**Issue by sonictk** [x13pixels/remedybg-issues#135]
Currently, the only way that I'm aware of to get a variable from the watch window to the memory viewer is to type its name directly, or its address.

It would be helpful to have a context menu option "send to memory window" or similar (drag-and-drop, perhaps?) UX alternative to make this task easier when attempting to inspect the memory of a variable.

**Comment by x13pixels** [comment]
Added "Send to Memory Window" option to context-menu of watch window.
