### ISSUE TITLE
Enum with custom base is not properly shown in watch window

### ISSUE THREAD

**Issue by LowySt** [x13pixels/remedybg-issues#137]
Example:

    enum Test1 : u8 { 
    HERE = 0,
    THERE,
    };

    enum Test2 : u8 { 
    FOO = 3,
    BAR,
    };

    struct Example {
    Test1 p;
    Test2 h;
    };

When looking at an istance of the Example struct in the watch window, the value of Test1 p is going to be shown as if it was a 32 bit integer (like a standard enum) rather than a 8 bit integer (like the narrower type it should be).

It really confused me when modifying Test2 h changed the value shown in the watch window for Test1 p, because the debugger looked at 4 bytes in memory starting from Test1 p's address.

**Comment by x13pixels** [comment]
Added handling for enumerations with a specified integral type.
