### ISSUE TITLE
Debugger either shows wrong instruction or jumps instead of stepping

### ISSUE THREAD

**Issue by LowySt** [x13pixels/remedybg-issues#139]
![RemedyBug](https://user-images.githubusercontent.com/15781149/67985197-94fcd600-fc28-11e9-8dcc-9153a6ec47e2.png)

As shown in the image, this is the part of the code I am currently in. Trying to step over (F10) jumps the program to a completely different point (It cannot just be a wrong display of the current instruction, because according to the assembly window we ACTUALLY are where the cursor shows. The call op a little bit after is the ls_alloc() call).

Trying to step into (F11) steps first directly into the ls_alloc() function. Once out of the function the cursor remain at the breakpoint in the source window. 
Stepping again (F11) will move me inside the ls_memcpy() function. Again once out of the funcion the cursor will remain at the breakpoint. 
The last step into will completely jump to another part of the code, the same part that would've been reached if step over (F10) was used instead of stepping into.

The part of the code reached after the step over is outside the function and is actually *before* the function call, not after (though I'm inside a loop, so It's probably jumping to the next iteration of the loop).

The sections of the source unreachable during stepping are also unreachable if a breakpoint is placed there (The breakpoint's icon will show a question mark while the program is running, and is never reached).

I *know* those sections are reached because the program actually performs correctly when executed.

Just FYI string is a normal c++ struct:
`struct string {
    char *data = 0;
    u32 len = 0;
    u32 size = 0;
}`

**Comment by x13pixels** [comment]
Can you please add the version of RemedyBG, the compiler used, compiler version info, and compiler flags used. Also, if possible, sending the PDB to remedybg@protonmail.com would help expedite reproducing this.

Thanks!

**Comment by LowySt** [comment]
email sent with information
