### ISSUE TITLE
Using delete button in watch window removes other expressions

### ISSUE THREAD

**Issue by seventh-chord** [x13pixels/remedybg-issues#140]
I'm using version 0.2.8.9

Steps to reproduce:
 - Add at least two expressions to the watch window
 - Go into edit mode on the first expression
 - Move somewhere within the string
 - Press delete to remove a character from the expression

At this point **a)** a character is deleted from the first expression and **b)** the entire second expression is deleted. **b)** is somewhat unexpected :)

I suppose this is related to #73

**Comment by x13pixels** [comment]
Using the Del key while editing a watch expression will no longer delete a watch expression inadvertently.
