### ISSUE TITLE
Double/triple-click selecting words/lines

### ISSUE THREAD

**Issue by sonictk** [x13pixels/remedybg-issues#141]
Something that drives me a little crazy in RemedyBG (and I'm not sure if it's intentional UX or not) is the behaviour surrounding double/triple-clicks. In most text editors, a double-click is an action to select a word, while a triple-click selects the entire line that the cursor is hovering over. As of the current release (2.8.9), it seems like a double-click already results in an entire line selection, with no way to easily do a word selection. 

Word selections are useful for easily doing things like selecting a variable name (in order to copy it to the watch window), along with just following the general editor UX conventions that have been established elsewhere. I understand that RemedyBG's goal is _not_ to be like other debuggers in the first place, but if this is something simple to modify (not sure if this is ImGui-related or not), I wonder if you could consider changing the UX so that double/triple-clicks behave similarly to other editors? 

Thanks!

**Comment by x13pixels** [comment]
Will do.
