### ISSUE TITLE
environment variables

### ISSUE THREAD

**Issue by christopher-hesse** [x13pixels/remedybg-issues#143]
Hey, I'm having a great time using RemedyBG, but I can't find an easy way to set environment variables for a particular run.  I could set them globally on the system of course, but these are project-specific values, like PATH or some internal variable that can't easily be passed on the command line.

Is there any interest in adding this?  It seems like it would fit in the session menu under "working directory".

**Comment by x13pixels** [comment]
I had added them to the debug engine a while back but never into the UI. I'll put this on the list for the next release.

**Comment by x13pixels** [comment]
[0.3.0.0] Added UI for adding environment variables for a session. Includes option for inheriting environment from parent process.
