### ISSUE TITLE
Adding default value to struct member makes the entire file unreachable by breakpoints

### ISSUE THREAD

**Issue by LowySt** [x13pixels/remedybg-issues#145]
I've got a repro for that. Sorry for the messy code, I had to extract it from my working project, and I couldn't make it smaller than this without changing the code too much.

The repro is for Windows, made up of 2 files:

main_repro.cpp
   here we've got a couple typedefs and functions that the actual offending file will use
   plus the winmain which just calls into the other file

openType.h
   This is the offending file. The problematic struct is OpenType_DictData

When trying to change the member "u32 CharstringType" from not having a default value, to having one:  "u32 CharstringType = 2" remedy will no longer be able to set breakpoints inside that file.

Here's the build options:
```
SET OPTS= -Od -I F:\ProgrammingProjects\AddIncludes\PlatformAndTools\ -FC -GR- -EHa- -nologo -diagnostics:column -Zi -F16000000

SET LIBS=kernel32.lib user32.lib gdi32.lib gdiplus.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib Opengl32.lib Glu32.lib winmm.lib

pushd outrepro
cl %OPTS% \repro\main_repro.cpp %LIBS%
del *.ilk
del *.obj
popd

```

Had to upload the files as .txt since github doesn't apparently support attaching code files.

[openType.txt](https://github.com/x13pixels/remedybg-issues/files/4394797/openType.txt)
[main_repro.txt](https://github.com/x13pixels/remedybg-issues/files/4394798/main_repro.txt)

**Comment by LowySt** [comment]
By the way, using Remedy 0.2.9.2

**Comment by x13pixels** [comment]
[0.3.0.0] Confirmed fixed.
