### ISSUE TITLE
Quotes don't get copied over to the commandline arguments correctly

### ISSUE THREAD

**Issue by Jasper-Bekkers** [x13pixels/remedybg-issues#148]
When invoking remedybg from the commandline like this:

`remedybg target\debug\my_thing.exe -f "Path with spaces.gltf" -s 0.001`

The quotes become missing in the Session -> Command Arguments window

![image](https://user-images.githubusercontent.com/49594/78558134-6526af80-7812-11ea-8f5a-3ed6b1e2058d.png)

**Comment by x13pixels** [comment]
Now properly initialize command from command-line arguments when
there are spaces or escaped quotes in the argument.
