### ISSUE TITLE
F10 hotkey for stepping seems to work oddly

### ISSUE THREAD

**Issue by sonictk** [x13pixels/remedybg-issues#150]
Currently, ever since updating to RemedyBG 3.0.0 (and now 3.0.2) I'm having an issue where when I hit F10, the instruction indicator disappears, as if it's stepped into an internal function, I have to press F10 several times for it to re-appear at the next line. 

Strangely enough, if I use the Control > Step Over (line) option from the menu itself, this doesn't happen and everything works as expected. 

I'm not restoring RemedyBG from an existing debug session or anything. Is there anything I can do to try and diagnose what might be happening when the indicator "disappears"?

**Comment by x13pixels** [comment]
If the disassembly window is in focus (yellow box around window) then F10 steps over single instruction rather than line. If this isn't the case then maybe take a look at call stack / disassembly to see what the RIP is set to. If this happens at a particular spot, the assembly instructions around that location would help track down the problem. Thanks!

**Comment by sonictk** [comment]
Ok, this is weird. So the disasm window is not in focus, but the issue only happens if I'm working with the Attach to Process workflow (in this case I'm attaching to Photoshop). In that case, when I'm stepping through the code, the `rip` register value in the Registers window doesn't seem to update correctly. It doesn't seem to happen in particular at any specific spot either, it can even happen on just simple declarations. I recorded a video to illustrate this better:

https://youtu.be/_x_uW2RYiME

(Every time you see the cursor disappear, that's me pressing F10 twice; I swear my PC is fast enough to step one instruction without that much lag time xD)

I just tried using RemedyBG on my own D3D12 test engine and tried stepping through the code there, and while stepping works, the registers window doesn't seem to be updating accurately either; sometimes `rip` doesn't change when it should, and the values between the Registers window and the Watch window don't seem to line up. Couple of example screenshots:

![image](https://user-images.githubusercontent.com/2504199/78857041-26912080-79dd-11ea-8ef3-2b51a5f1857b.png)

![image](https://user-images.githubusercontent.com/2504199/78856934-e3cf4880-79dc-11ea-9db9-5d1945587453.png)

Not sure if the two issues are related?

**Comment by x13pixels** [comment]
Please let me know if 0.3.0.4 is work better for you (stepping, attaching, registers, and so forth). Thanks!

**Comment by sonictk** [comment]
Hi!

The good news is that it looks like the issues mentioned in this ticket are all fixed. Stepping now works reliably without me needing to hit the hotkey twice. Detaching and attaching to the process again seems to work without causing duplicate breakpoints to appear. Registers in the register window now update fine.

The bad news is that stepping over instructions is now incredibly slow. It looks like it's waiting for the registers window to refresh before allowing me to step to the next instruction (which makes sense), but the update is _much_ slower than before. I tried this as well on my normal test D3D12 engine which also exhibits the same issue, though not for every single line. I'm not sure, but I think this slowness didn't present itself in 3.0.3 (I stupidly deleted my version of 3.0.3, so I can't download it again from the website to double-check)

The other piece of bad news is that it looks like Re-attach to Process isn't working, or least not in the way that I expect, which I also demonstrate in the video: it appears permanently greyed out and I can't see how to enable it, even after attaching/detaching from the same process multiple times manually.

I've recorded a video of the regression in stepping-over behaviour and the Re-attach to Process issue, available here: https://youtu.be/KaBQqKHISQI

**Comment by x13pixels** [comment]
My guess is that the stack unwind code is taking some bit of time for some reason. Can you take a look at the threads and their associated call stacks to see if this is the case? In any case, I'll be happy to purchase a copy of Photoshop to see if I can better reproduce your environment here. You can email my protonmail with setup instructions if this is an option. Thanks for all your help!

**Comment by sonictk** [comment]
> My guess is that the stack unwind code is taking some bit of time for some reason. Can you take a look at the threads and their associated call stacks to see if this is the case? 

I recorded two additional videos that hopefully provide you some information:

https://youtu.be/kIY6d-jr2JE

https://youtu.be/a5hSU7IEyy4

The first one shows the issue with the main thread and the callstack while stepping. It also shows a new issue (sorry, I seem to have a lot of these!) that RemedyBG hangs when I click "Detach", and the only resolution is to force quit RemedyBG, which takes down Photoshop with it.

The second video shows various callstacks for various threads while I'm stepping through. It also shows that the "Stop Debugging (detach)" option actually works better in this case for detaching the debugger, which actually leads me to ask: what is the difference between the two anyway?

> I'll be happy to purchase a copy of Photoshop to see if I can better reproduce your environment here. 

I think Photoshop has a 7-day trial period that should hopefully cover this. I'll try to find all my issues in this workflow first so that you can tackle them all at once! :P I'd be happy to provide source code and setup instructions, since it's all [public](https://github.com/sonictk/ps_cpp_recipes) anyway. I don't actually know your protonmail account; if you could DM me on [Twitter](https://twitter.com/ylsiew/) or something, I'd be willing to assist in recording/writing down a list of repro steps.

Thanks for investigating this issue! Really appreciate it, and starting to use RemedyBG now for debugging some other standalone binaries to give it a proper test drive.

**Comment by x13pixels** [comment]
These issues should be addressed in 0.3.0.6.
