### ISSUE TITLE
Spaces in folders mess up the argument list

### ISSUE THREAD

**Issue by IRooc** [x13pixels/remedybg-issues#153]
RemedyBG version: 0.3.0.2 on windows 10 

When you have this program:
```
#include <stdio.h>
int main(int argc, char *argv[]) {
   printf("Hello, World!\n");
   if (argc > 1) {
       printf(argv[1]);
   }
   return 0;
}
```
Compile to eg main.exe

And setup RemedyBG like this:
Command: c:\path withspace\main.exe
Command Args: testvar

Expected output
```
Hello, World!
testvar
```

Actual output:
```
Hello, World!
withspace\main.exe
```

Putting qoutes around the command won't work and gives  "executable not found"

Thanks for the work by the way!

**Comment by x13pixels** [comment]
[0.3.0.3]
