### ISSUE TITLE
Multiple select in the watch window

### ISSUE THREAD

**Issue by sonictk** [x13pixels/remedybg-issues#160]
Small thing (or maybe not so small, IDK), but would it be possible to be able to multi-select items in the Watch window? That way I can select a couple of items to remove at once. (The usual modifiers Shift/Ctrl-click to select and add to selection for items is what I'm referring to.) Otherwise I end up usually just highlighting the first item and holding down Del to delete everything, and then add each item that I want again manually.

**Comment by x13pixels** [comment]
[0.3.2] Multiselect has been added in watch (and other) windows.
