### ISSUE TITLE
Types qualified with namespaces are not parsed correctly in watched expressions

### ISSUE THREAD

**Issue by edwinst** [x13pixels/remedybg-issues#161]
Steps to reproduce:

1. debug a program using a variable of type (struct "bar" in a namespace "foo")
2. add a watch expression for this variable (works and shows the type correctly, including its namespace "struct foo::bar")
3. use the struct name, for example to add a type-cast watch expression "*(foo::bar *)ptr" --> fails with "Parse error".

**Comment by edwinst** [comment]
Reported for version 0.3.0.4.

**Comment by x13pixels** [comment]
Parsing of namespaces was added in 0.3.1.0.
