### ISSUE TITLE
Data members in base sub-objects (except for the first one) are not correctly evaluated when using multiple inheritance

### ISSUE THREAD

**Issue by edwinst** [x13pixels/remedybg-issues#163]
Reporting for version 0.3.0.4: When one looks at a derived class with multiple base classes, the data members in the base sub-objects, except for the first base, are evaluated wrongly.

For a minimal example to reproduce see below. The "printf" statement correctly prints "a=1 b=2 c=3" but remedybg watch window shows "a=1 b=1 c=3":

    struct BaseA {
        int a;
    };

    struct BaseB {
        int b;
    };

    struct Derived : BaseA, BaseB {
        int c;
    };

    int main()
    {
        Derived derived;
        derived.a = 1;
        derived.b = 2;
        derived.c = 3;
        printf("a=%d, b=%d, c=%d\n", derived.a, derived.b, derived.c);

        return 0;
    }

**Comment by x13pixels** [comment]
Fixed for 0.3.0.6.
