### ISSUE TITLE
Locals Window

### ISSUE THREAD

**Issue by sonictk** [x13pixels/remedybg-issues#164]
This may have been a design decision, but is there any reason why RemedyBG doesn't have a Locals/Autos window like most other debuggers? It's certainly not a showstopper, but sometimes it's nice to be able to just view stuff without having to manually add everything that I want to inspect to the Watch window.

**Comment by x13pixels** [comment]
You can use the __locals synthetic variable in the watch window.

**Comment by sonictk** [comment]
Hey @x13pixels, I tried looking for this info, but couldn't find it anywhere, do you have a list of the available synthetic variables? Right now apart from `__locals` I see `__threadid` and `__params` in some of the release notes, but it'd be nice if you could quickly run down everything that's available. 

Thanks!

**Comment by x13pixels** [comment]
At the moment, these are documented under "Synthetic Structures" in the README.txt file. Right now, only __locals and __params are supported but I'll be adding more. In any case, I think I need to put something in the UI for both these synthetic structs and for available formatters (e.g., ",db", ",x", and so forth).
