### ISSUE TITLE
RemedyBG no longer auto-updates when source file is modified on disk, crashes on occasion under unknown circumstances

### ISSUE THREAD

**Issue by sonictk** [x13pixels/remedybg-issues#165]
I'm currently running into a very odd issue here: so it appears that on occasion, RemedyBG will no longer sync files that have been modified on disk any longer. I'm also running into an issue where sometimes opening a source file itself crashes RemedyBG when the file has no contents in it, but if it has contents, it open (but fails to sync after). It seems to be related to the path of the source file somehow, since if I move it to my desktop and open it from there, the problem seems to disappear.

I'm also getting a crash if I open the first problematic source file, and then open a second source file which has the exact same name except a `_1` suffix instead.

Because I don't know if this is really related to filenames or not, I've uploaded several minidumps that were captured at the time of crash instead. Hopefully that will help in narrowing down the issue:
https://1drv.ms/u/s!Agq86GnpCQaLl518mmhMd_E_GmxhYA?e=duKpmX

**Comment by x13pixels** [comment]
Fixed in 0.3.0.6.

Fixed crash with zero length files.

Also, really strange behavior with FindFirstFileNotification for zero length files. Had to add additional filters (FILE_NOTIFY_CHANGE_LAST_WRITE wasn't enough to get notified that something in the directory changed, apparently).
