### ISSUE TITLE
char and wchar_t misdisplayed in watch window

### ISSUE THREAD

**Issue by seventh-chord** [x13pixels/remedybg-issues#166]
I've noticed three separate issues with char/wchar_t types in the watch window. Please let me know if you want me to split this up into separate issues here.

I've been using version 0.3.0.5, compiling with msvc 19.22.27905 (only passing /Zi), and am running windows 8.1.

1. When there is a percentage sign in a `char *`, if it is expanded in the watch window the percentage sign will draw as an empty character literal: `37 ''` instead of `37 '%'`.

2. When specifying a length for `wchar_t` literals in the watch window (`my_wchar_array, 6`), only half the number of characters specified are displayed in the value field (i.e. if `my_wchar_array = L"nice"` the value field displays `{ ... } 0xfoofboof "nic" ` if length is 6). The correct number of characters are still displayed in the expanded view though.

3. When expanding a `wchar_t *` value in the watch window, the string displayed in the value field for the expanded item gets messed up when the focus moves from the watch window to the source window (i.e. if `foo = L"a"` and I expand `a` in the watch window, the expanded entries value changes from `97 'a'` to `97 'a?`)

**Comment by x13pixels** [comment]
Fixed for 0.3.0.6
