### ISSUE TITLE
Some way to edit hotkeys

### ISSUE THREAD

**Issue by Yavor-Ivanov** [x13pixels/remedybg-issues#167]
Hello, I recently started using remedybg. My keyboard has a problem with the F keys (they only sometimes register). In Visual Studio, I worked around this by changing the hotkeys to CTRL+(other key here).

I don't use the F keys in any other applications, so I'm not in a hurry to find a new keyboard. Is there a way to edit the hotkeys in Remedy? I couldn't find anything in the interface, but perhaps there is some configuration file I can edit somewhere.

**Comment by x13pixels** [comment]
There is no way to do this currently. Sorry! It will definitely be a part of a future release, though.

Closing as a duplicate of #30

**Comment by x13pixels** [comment]
Also requested by @Perlind
