### ISSUE TITLE
Add the ability to copy the address of a breakpoint

### ISSUE THREAD

**Issue by simonvanbernem** [x13pixels/remedybg-issues#168]
Small quality of life request:
I set a data-breakpoint through an expression. Then the breakpoint was hit, but I am in a scope where that expression is not valid anymore. It would be helpful, if I could copy the address from the breakpoint directly, to inspect that value. It already is displayed, which wants me to be able to copy it.

**Comment by x13pixels** [comment]
Added "Copy Address" to context-menu in Breakpoints window.
