### ISSUE TITLE
Named session is not detected when closing with changes

### ISSUE THREAD

**Issue by sir-pinecone** [x13pixels/remedybg-issues#170]
I have a session file named `test.rdbg`. If I open it using `remedybg.exe test.rdbg`, make a change (e.g. close a file) and then exit Remedy, it asks if I want to save changes to the unnamed session. Clicking yes will open the dialog to save a new session file.

If I open the session file from within Remedy and repeat the same steps then it correctly detects it and saves to disk.

Note that I tried this with auto-save enabled/disabled and saw the same behaviour.

**Comment by x13pixels** [comment]
We now obtain the full path name of RDBG in session.

This fixes the problem where the session file opened is not an absolute path.
