### ISSUE TITLE
Ability to close tabs using the middle mouse button

### ISSUE THREAD

**Issue by Manuzor** [x13pixels/remedybg-issues#171]
Since there are no x-buttons next to individual tabs anymore (related #132), it takes 2 clicks to close an unfocused tab (either select and hit the x button on the far-right, or right click and "Close").

From other applications using tabs (web browsers, text editor, windows explorer preview), I'm used to close individual tabs by middle-clicking on them. Would be nice to see this common UI-feature in remedybg as well.

**Comment by x13pixels** [comment]
The change that removed close buttons ImGui code affected the middle-click behavior. Reverted this change.
