### ISSUE TITLE
Feature Request: Watch window interprets HRESULT values

### ISSUE THREAD

**Issue by troygnichols** [x13pixels/remedybg-issues#172]
Thank you for this fantastic debugger!

I noticed the Visual Studio debugger does something kind of helpful that Remedy does not do yet. VS is somehow aware of the semantic meaning of HRESULT values, and will show that meaning in the Watch window instead of the raw value. 

![VSCode-HRESULT](https://user-images.githubusercontent.com/221013/86547555-65187780-bf07-11ea-83f0-436365a3810a.png)

Remedy doesn't seem to know anything special about these values.

![Remedy-HRESULT](https://user-images.githubusercontent.com/221013/86547594-75305700-bf07-11ea-9808-4daf790a7d78.png)

I'm using this tool to follow along on the Handmade Hero course, and am pretty new to C/C++ on Windows, so I have no idea if what I'm asking for is possible, but I thought it could be useful.

Thanks again!

**Comment by x13pixels** [comment]
Implemented as value: description. There isn't a readily available mapping back to the symbolic constant (e.g., S_OK or S_INVALID) and I didn't want to make a giant table of these. The descriptions, though, can be obtained programmatically via `FormatMessage`.

![image](https://user-images.githubusercontent.com/3690363/96385621-15cb1f80-1163-11eb-90f2-4c9908eb013e.png)
