### ISSUE TITLE
Watch window shows different output for pointer and value

### ISSUE THREAD

**Issue by fda0** [x13pixels/remedybg-issues#173]
For some reason my struct is interpreted incorrectly by the watch window if I pass it by pointer to a function. There is no problem if I view the value.
It happened in a small project. I never had problem with remedybg before. I cut off most of the code and the problem still persists. 

Currently it cuts off last 4 fields from the struct (in the watch window).
30 minutes ago I had very similar bug. It showed that values array has 10 members instead of cutting last fields. It resulted in the whole struct being interpreted incorrectly. 

Source: https://gist.github.com/uint8t/1758943c86d1f3fc6251cf3ccd2347ad

![remedy_bug_00](https://user-images.githubusercontent.com/64565772/87722154-e13c7600-c7b7-11ea-98e9-e80c9aadfe54.PNG)

Maybe you need it - build (from MSVC) with source code:
[build.zip](https://github.com/x13pixels/remedybg-issues/files/4934153/build.zip)

**Comment by x13pixels** [comment]
Appreciate the repro. Was able to get this fixed with it.
