### ISSUE TITLE
Selecting text in the code window is based on the left edge of characters.

### ISSUE THREAD

**Issue by ebeachly** [x13pixels/remedybg-issues#175]
When you click and drag your mouse across the code window from left to right to select some text, you have to click on the character before the one you actually want to select, and then drag right. You should be able to start the selection by clicking on the left half of the first character you want to select, but instead that starts the selection at the character to the right. The end of the selection is similarly determined by the left edge of characters.

This is somewhat annoying when I'm copying an expression from the code window into the watch window, because I rarely select the correct text on my first attempt.

It would work better if the selection was based on the center of the character, or slightly to the right of center (so that clicking on the center of the first character will select it when dragging from left to right). Text selection when editing an expression in the watch window works nicely, so copy that.

Thanks for making this debugger!

**Comment by x13pixels** [comment]
Unless I'm misunderstanding I'm not seeing this. Maybe it is font dependent? Maybe tabs vs. spacing or the tab setting?

This image is a debug view showing the hit rect for each character. Each character __should__ be selectable from the previous character's midpoint up to the character's midpoint.

![image](https://user-images.githubusercontent.com/3690363/95695188-cf763d80-0c03-11eb-8435-0c99e3832248.png)

**Comment by ebeachly** [comment]
Okay, text selection appears to work correctly when I start remedy, but becomes incorrect after some amount of usage. Here's a video showing the incorrect behavior (it's more obvious at the end). I'll see if I can figure out how to reliably reproduce it.
[video.zip](https://github.com/x13pixels/remedybg-issues/files/5362478/video.zip)

**Comment by ebeachly** [comment]
Here's how to reproduce it:
1) Start Remedy 0.3.0.7
2) Open the attached file
3) Scroll down to line 154
4) Rapidly left click on the 'a' at the beginning of the line 20 times. The entire line should toggle between black and blue with each click.
5) Try to select some text. It should now select text based on whether your selection includes the left edge of the character.
[Application.txt](https://github.com/x13pixels/remedybg-issues/files/5362570/Application.txt)

**Comment by x13pixels** [comment]
Fixed text selection in lines containing tabs.
