### ISSUE TITLE
Unremovable empty line in watch window

### ISSUE THREAD

**Issue by staslisetsky** [x13pixels/remedybg-issues#177]
Hello, this just happened in the latest version 0.3.0.7
I was editing something in the watch, and this extra empty line appeared at the end that I'm unable to remove.

![image](https://user-images.githubusercontent.com/16389158/96069263-1d0dd700-0e9e-11eb-8c94-cd37ad3d372b.png)

I can't repro it unfortunately. I think I was holding 'del' to remove a bunch of fields, and then added a new field. I did it very fast and haven't noticed what exactly happened.

Here's the .rdbg file with the saved watch state. The extra line is there and bugged behavior can be observed when I load it.
https://stas.ams3.digitaloceanspaces.com/graphene.rdbg

**Comment by staslisetsky** [comment]
ok after a bit of banging on keys here's the repro:

- put a value into an empty watch, hit enter. it will auto-jump to next line
- go back up 1 line (with up arrow key) and type text to start editing the 1st line
- erase all text in the line with backspace, and press down arrow to jump to next line
- it will keep 1st line empty - and now it cant be removed

not sure if this is fixed already in the new version, but I hope this helps.

**Comment by x13pixels** [comment]
Fixed for 0.3.1.0. Appreciate the concise repo steps!
