### ISSUE TITLE
0.3.0.7 Crash when stepping into function

### ISSUE THREAD

**Issue by ghost** [x13pixels/remedybg-issues#178]
I was trying to debug a certain part of my program and remedybg silently crashed/closed after I tried to step past the function setup (the first step you need to make when you step into a function to setup the stack and stuff) in parse_expr.

What I had to do to repro it was:
- open the rhr\build\win32_rhr.rdbg session in remedy
- change Session>Command to the full path of rhr\build\win32_rhr.exe
- make sure the working directory is rhr\build and the argument is ..\demos\foo.rhr
- press F10 to start debugging
- set a breakpoint on line 887 in win32_rhr.cpp
- press F5 5 times (until the latest output in the console is "`(normal=((((3*4)+(5*6))+(7*8))+(9*0)))`")
- right click line 882 and run to cursor
- F11
- F10
- rememdy closes silently
- error shows in windows event viewer (i saved the event in case you need it)

I just attached the entire folder since I couldn't figure out what exactly was causing it.
[rhr.zip](https://github.com/x13pixels/remedybg-issues/files/5386483/rhr.zip)
Deleting the rdbg file and remaking it seemed to remove the crash.

Another error I found was when I moved the rhr folder from w:\_crashes\remedybg\ to w:\_crashes\remedybg\rhr_5_step_parse_expr (i'm pretty sure it was that but i might be wrong) and couldn't start debugging for what the message box that popped up said was an unknown reason. Unfortunately I can't repro this one for some reason.

**Comment by x13pixels** [comment]
1. If the image handle isn't given in the CREATE_PROCESS_INFO event (for whatever reason) we can still try opening the file to obtain info from the PE header. This gets rid of the popup "unknown reason" in these cases.

2. Fixes lower bound of string preview size. In the case where a variable is not yet in scope, an expression like `var.data, str var.len` could cause a crash if `var.len` evaluated to a negative number.
