### ISSUE TITLE
0.3.0.7 Extra character appended when copying variable to watch window

### ISSUE THREAD

**Issue by ghost** [x13pixels/remedybg-issues#179]
![image](https://user-images.githubusercontent.com/39637437/96374185-051da800-1169-11eb-88d1-bc3e2378c326.png)
When I was copying variable names from the text viewer to the watch window, a seemingly random character would be appended to the end. I say seemingly random because it looks like the character might come from an above watch variable/row.

Repro
- Double click a variable name to select it
- ctrl+c
- Click on the open slot below the watch variables
- ctrl+v
- Click on one of the watch varibables above (I think this might be the problem)

Edit: After trying some more, it only ever happens when clicking the above watch variables.

**Comment by x13pixels** [comment]
Fixed zero termination of edit buffer.
