### ISSUE TITLE
0.3.0.7 Watch window page up/down

### ISSUE THREAD

**Issue by ghost** [x13pixels/remedybg-issues#180]
If you double click an exisiting entry in the watch window (so that you can edit it) and press either page up or page down, that entry gets copied to either:
- Page-up: override the top-most entry, erasing the one there
- Page-down: make a new entry at the bottom
I don't know if this is intentional, the page up definitely doesn't, but he page down one could be kind of handy since if you edit an entry and press page down, the new edited version appears at the bottom and the old one reverts to before the edit.

**Comment by x13pixels** [comment]
Fixed Page Up/Down not saving off / terminating current edit.
