### ISSUE TITLE
0.3.0.7 Breakpoints grey out and a new duplicate file tab is created

### ISSUE THREAD

**Issue by ghost** [x13pixels/remedybg-issues#181]
Sometimes when I start debugging, my breakpoints go greyed out/transparant with a question mark and a new tab with the same file file that had those breakpoints open up. I end up with 2 tabs of the same file
- One has the breakpoints that are now greyed out
- The other is the one I'm actually stepping through, but has no breakpoints

So far I can't find a reliable repro for it, but it does happen often.
I was thinking it might have something to do with editing the file, but nothing I try repros it. 
I'll definitely keep trying to find a repro for it next time it happens and will update here if I make progress.

Note: This does seem quite similar to issue #151

Edit: [win32_rhr.zip](https://github.com/x13pixels/remedybg-issues/files/5419840/win32_rhr.zip) This is an rdbg file where this happens. I can upload the rest of the files if you want me to.

**Comment by x13pixels** [comment]
I believe this has been fixed in 0.3.1.0. I will leave it open until we can confirm. There was a problem reading the proper entry in the global string table.
