### ISSUE TITLE
Feature: Start debugging by doing 'Run to Cursor'

### ISSUE THREAD

**Issue by ghost** [x13pixels/remedybg-issues#182]
It would just be a nice quality of life thing to be able to press Crtl+F10 or right-click instead of having to set a breakpoint, F5, then remove the breakpoint.

**Comment by x13pixels** [comment]
This should work now unless I'm misunderstanding.

![image](https://user-images.githubusercontent.com/3690363/97235414-332e6800-17b9-11eb-9600-2f5ff7b8ae1f.png)

**Comment by ghost** [comment]
Sorry, I just noticed how unclear I was. I meant when you're not debugging. Like you actually start the debugging session by doing Run to cursor. I actually just tested it now and I can start debugging by pressing Ctrl+F10, but I can't right-click the text at all when not debugging.

**Comment by x13pixels** [comment]
No worries. Thanks for the clarification. Fixed for 0.3.1.0.
