### ISSUE TITLE
Vim-style navigation

### ISSUE THREAD

**Issue by dstasio** [x13pixels/remedybg-issues#183]
I'd like to propose the addition of secondary keys (or even optional, to be activated by those who want it) that mimic the behavior of the arrow keys. 
They would be the keys H, J, K, L to move respectively left, down, up and right, as you do in vim.

To clarify, I'm not suggesting support for all of vim's commands, just the basic four.

**Comment by x13pixels** [comment]
Added J/K keys for text window / disassembly window. There isn't a cursor drawn so H/L don't make sense at the moment.

**Comment by dstasio** [comment]
First of all, thank you! 
As for H and L, I was thinking about the watch window, to expand and collapse structs.
