### ISSUE TITLE
0.3.1.0 Crash when deleting exe path command

### ISSUE THREAD

**Issue by ghost** [x13pixels/remedybg-issues#184]
[win32_rhr.zip](https://github.com/x13pixels/remedybg-issues/files/5469962/win32_rhr.zip)
When I try to delete the exe path under Session > Application and Parameters > Command, remedy crashes.
You can either select the entire path and press backspace/delete or backspace the path one character at a time until you reach "W:\", remedy crashes when you try to backspace the '\'.

EDIT: Remedy also crashes when I try to start debugging, but it fixed when I made a new session. Likely due to version issues. I saved the other files if you need it.

**Comment by x13pixels** [comment]
Fixed crash in handling of empty working directory.
