### ISSUE TITLE
0.3.1.0 Set Next Statement and Step Over (Instruction) are double-bound to Ctrl+Shift+F10

### ISSUE THREAD

**Issue by ghost** [x13pixels/remedybg-issues#185]
When debugging, I move the selected line to a line that isn't the current instruction/line and press Ctrl+Shift+F10, remedy first does Set Next Statement and then Step Over (Instruction).

**Comment by x13pixels** [comment]
Removes overloaded Ctrl+Shift+F10 hotkey use for stepping by instruction granularity. Now that you can focus on the disassembly window and use F10/F11 this is no longer necessary.
