### ISSUE TITLE
0.3.1.0 Crash when trying to access members of a parenthesized expression in watch/memory view

### ISSUE THREAD

**Issue by IntendedConsequence** [x13pixels/remedybg-issues#186]
RemedyBG crashes whenever I access struct members via . if I put what's left of the dot in parens. Example:

Vec4f color;
color.rgb - no crash
color.test - no crash, error: union field not found
(color).rgb - crash
(color).test - crash

it's the same with pointers and arrows -> btw, no parens - no crash, with parens - crash
First time crashed in memory view, after that all my repros come from watch window. Tried in two executables, compiled by clang-cl. Also reproduced on WIN32_FIND_DATAW struct.

**Comment by x13pixels** [comment]
186. Fixed crash in handling of cast vs. expression diambiguation.
