### ISSUE TITLE
0.3.1.0 F10 steps into default member list for struct

### ISSUE THREAD

**Issue by ghost** [x13pixels/remedybg-issues#187]
```
struct Ast_Type {
    int l0 = -1;
    int c0 = -1;
    int l1 = -1;
    int c1 = -1;
};

int main() {
    Ast_Type data_type = {};
}
```
I'm not sure if this is intentional or not, but when stepping though this code with F10, remedy steps into Ast_Type and though each default value. I would've expected it to step over the line in main() with one button press.

**Comment by x13pixels** [comment]
Checked and this is the expected behavior based on the debug information emitted by MSVC. There are line info entries for the initialization of each default value which is why the step-over operation behaves as reported.
