### ISSUE TITLE
0.3.1.0 Extra watch/memory windows become detached from group pane when applying saved layout

### ISSUE THREAD

**Issue by sir-pinecone** [x13pixels/remedybg-issues#188]
I enabled some extra watch and memory windows and then attached them to some existing group panes:

![image](https://user-images.githubusercontent.com/40753/98012034-9b3b0a80-1dc6-11eb-8b6c-0b24078380fe.png)

I saved the new layout and then reapplied it. Memory 2, Memory 3, Watch 2 and Watch 3 windows detach from their parent pane and float on top of one another, blocking the previous parent until you resize the RemedyBG app window. Applying the layout again doesn't change the position of the extra windows, it only re-opens them if they were closed. 

The only consistent fix I found so far is to close the extra windows, restart Remedy and then apply the layout. 

Btw, I did various permutations of closing windows and reapplying the layout and sometimes one of the extra windows would be placed correctly. I didn't keep track of what I was doing though, so I don't know the exact steps to replicate it. I figured patching the main bug will clear up this inconsistent behaviour.

**Comment by x13pixels** [comment]
Fixed extra watch/memory windows interaction with layouts.
