### ISSUE TITLE
0.3.1.0 Crash when clicking Session/Control with certain .rdbg session

### ISSUE THREAD

**Issue by IntendedConsequence** [x13pixels/remedybg-issues#189]
Other sessions seem to work fine, but this particular one stopped working. It might have got corrupted when I worked on repros for #186, I'm not sure. Hotkeys F5, F10 and F11 also cause crashes. Here is the .rdbg that causes crashes:
[handmade.zip](https://github.com/x13pixels/remedybg-issues/files/5483208/handmade.zip)

I restored an older session file from a backup and it works just fine, here it is in case it helps. 
[handmade_working.zip](https://github.com/x13pixels/remedybg-issues/files/5483224/handmade_working.zip)

**Comment by x13pixels** [comment]
Fixed crash reading a session file containing processor breakpoint.
