### ISSUE TITLE
0.3.1 Crash when typing under Application and Parameters tab

### ISSUE THREAD

**Issue by aelthalyste** [x13pixels/remedybg-issues#190]
To reproduce, just open remedybg(without loading any session at all just download and open 0.3.1.0), try to type anything under Application and Parameters tab.

Reproducible one :
- If you try to type anything in environment tab, it just crashes.

Mostly crashing :
- When typing to "Command" or "Working Directory", it mostly crashes.

**Comment by x13pixels** [comment]
Duplicate of #184. Fixed for 0.3.1.1 release.
