### ISSUE TITLE
Feature req: Reorder watch window items with mouse drag

### ISSUE THREAD

**Issue by sir-pinecone** [x13pixels/remedybg-issues#191]
Sometimes I have a bunch of stuff in the watch window and want to rearrange the order without having to manually change the name values. This is particularly frustrating if I want to move it near the the top of the list. Being able to drag the rows around would be awesome.

**Comment by x13pixels** [comment]
[0.3.2] Ordering of watch expressions can now be altered with Ctrl+Up / Ctrl+Down.
