### ISSUE TITLE
Ctrl-Tab window display doesn't use the UI font size specified in window style options

### ISSUE THREAD

**Issue by luis-reyes-a** [x13pixels/remedybg-issues#193]
Maybe this is intentional but it'd be nice to allow the user to change the size of the font on this window. On some monitors text can be really small by default. Also it may be cool to switch between the different layout panels/windows instead of each window within each panel/window. Thanks!

**Comment by x13pixels** [comment]
Overlay displayed with Ctrl+Tab now uses the UI font.
