### ISSUE TITLE
Watch window values collapse on each successive run, masking nested values

### ISSUE THREAD

**Issue by mlabbe** [x13pixels/remedybg-issues#194]
I've been using Remedybg heavily for about a week as my daily driver and this is the main thing that's causing friction for me.

I have structs with nested values in the watch window.  I expand the values in the watch window to get at sub-fields.  Once I restart the debugging session and the values come into scope again the values are collapsed.  I have to manually re-expand them every time.

It would be fantastic if the collapse/expansion state of a watch variable persisted across executions.  

Thanks for improving my programming workflow.  I am excited and I think Remedybg is very promising.

**Comment by x13pixels** [comment]
Thanks for the kind words.

I have a fix for this in the works for 0.3.2.0. The nesting will be maintained across runs and if the resulting type of the expression remains the same (i.e., changing the formatting specifier won't mess up the expanded state).

**Comment by x13pixels** [comment]
[0.3.2.0] Expansion state of a watch variable will now be preserved across executions.
