### ISSUE TITLE
Clang's Address Sanitizer currently incompatible with remedybg

### ISSUE THREAD

**Issue by mlabbe** [x13pixels/remedybg-issues#197]
For those of us who are fortunate enough to be able to develop with the ~2x slowdown caused by Clang's address sanitizer, it would be nice to be able to have it on and compiled in during normal workflow.

Unfortunately, clang's address sanitizer causes a `0xc0000005` access violation when mapping memory before getting to main().  This access violation should be ignored.

In Visual C++ 2019 this is handled by disabling access violation via Debug > Windows > Exception Settings when using clang address sanitizer, and then manually re-enabling it. (Forgetting is also possible, which will lead to errors -- this is a bad workflow).

This issue would be partially solved by implementing #81 since being able to disable access violations would work.

However, that would bring Remedybg up to feature parity with MSVC -- requiring the user to manually toggle depending on build settings on a per-user basis (since msvc stores these flags on a per-user basis).  What would be incredible for Remedybg is to have an option to disable access violations before main() is reached, thereby avoiding access violations from virtual space expansion through access violation exceptions.

For the purposes of reproducing this problem I have created a stripped down git repo that will build an exe with clang inside msvc 2019 using clang toolchain:
https://github.com/mlabbe/msvc_asan_example

I recommend running the exe in msvc and see the access violation behaviour, and then try running the same exe in Remedybg and compare the issues.

**Comment by x13pixels** [comment]
[0.3.5.0] Adds support for AddressSanitizer.

Access violations due to a read/write into AddressSanitizer's shadow space are now skipped (allowed to be handled without halting execution). There is no UI required as this is detected and handled automatically by RemedyBG.

**Comment by croepha** [comment]
So, I think there might be a regression here
![remedybg-asan-about](https://user-images.githubusercontent.com/716462/144788510-b69b70a0-77ae-48f0-82b4-7ae3bd7fd0b4.PNG)
:

Compiled with 

    "C:\Program Files\LLVM\bin\clang-cl.exe" /MD -v  -fsanitize=address simple.cpp
    
And simple.cpp is this:


```
#include <stdio.h>

int main () {
    printf("1\n");
    printf("2\n");
    printf("3\n");
    printf("4\n");
    printf("5\n");
    printf("6\n");
    printf("7\n");
    return 0;
}
```

**Comment by croepha** [comment]
Binary runs fine outside of remedyBG

**Comment by croepha** [comment]
I also get an Exception thrown if I compile with VS 2019

    cl /fsanitize=address simple.cpp
