### ISSUE TITLE
latest visual studio c++ toolchain v14.28 generates bad debug information

### ISSUE THREAD

**Issue by ghost** [x13pixels/remedybg-issues#198]
Compiling with the latest Visual Studio Toolset generates bad debug information.
- MSVC v142 – VS 2019 C++-x64/x86-Buildtools (v14.28)

On win7 and win10 x64, I could no longer inspect variables.
Also while displaying the callstack (which contains garbage information) the framerate is so low, that you cannot navigate the ui anymore.

My command line without source:
    `cl -Fe<name> /nologo /EHsc /Zi /Od /DDEBUG /MTd /DEBUG <source> /link /INCREMENTAL:NO /NODEFAULTLIB:library <libpaths>`

I checked for /DDEBUG:FASTLINK and that caused  remedybg to not load any debug symbols, so that was not the problem (/DDEBUG is equal to /DDEBUG:FULL)

Solution for me was to switch to older toolset:
- MSVC v142 – VS 2019 C++-x64/x86-Buildtools (v14.27)
and adding "-vcvars_ver=14.27" as a argument to vcvars64.bat or vcvarsall.bat

e.g. in a short-cut, set target to:
    `C:\Windows\System32\cmd.exe /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat" -vcvars_ver=14.27`

Make shure not to remove the latest toolset (v14.28),
since Visual Studio Installer will also delete vcvarsall.bat (it is only part of the latest toolset).

I just purchased remedybg yesterday and was very dissapointed because of this behaviour at first.
I bought it specifically, since I was having problems with VS lately, but as it turns out updating VS was the problem (as usual).
Now remedybg works fine, but so does VS (but remedybg is still way nicer!!).

Thank you Microsoft for wasting a productive day!
But seriously Thank You George for an awseome lightweight debugger!

**Comment by x13pixels** [comment]
Fix for this will be released as part of 0.3.1.3 (tomorrow).
