### ISSUE TITLE
Hang setting breakpoint

### ISSUE THREAD

**Issue by slynch8** [x13pixels/remedybg-issues#199]
RemedyBG hangs if I set a breakpoint after the process has started. If I set a breakpoint before I start the debugger then the breakpoint works and I can debug, but I can't set any more breakpoints without causing the hang. 

I have a crash dump if that would be useful (triggered from TaskManager). Let me know and I'll send you a link.

RemedyBG Version: 0.3.1.3
Compiled with v142 toolset (VS2019)

**Comment by x13pixels** [comment]
Please send a link to protonmail address (listed in README.txt) when you get a chance. I'm not readily duplicating here.

**Comment by x13pixels** [comment]
Fixed reinitialization of module and corresponding debug information when a block is reused from freelist.
