### ISSUE TITLE
0.3.1.2 Namespaced variables that have const qualifier aren't parsed correctly by watch window

### ISSUE THREAD

**Issue by boulware** [x13pixels/remedybg-issues#200]
![image](https://user-images.githubusercontent.com/4677407/100768967-16d9a880-33c1-11eb-950f-404f374debe2.png)

As seen in the screenshot above, const-qualified members of namespaces aren't parsed correctly by the watch window. In this particular case, the behavior depends on where the const qualifier appears in the declaration.

```
namespace c
{
    float x = 1.23;
    const float y = 4.56;
    float const z = 7.89;
};

int main()
{
    return 0;
}
```

**Comment by x13pixels** [comment]
Fixed in 0.3.1.3 (available from download on itch.io). Appreciate the succinct examples btw!
