### ISSUE TITLE
Printing variables as binary in the watch window prints spurious data

### ISSUE THREAD

**Issue by sgstechnical** [x13pixels/remedybg-issues#203]
Tested on Remedy V0.3.1.6
When ',b' is added to a watched uint64_t variable, extra characters are printed on the end of the value.
![image](https://user-images.githubusercontent.com/6319729/102540327-c6439a00-40a6-11eb-9c17-ea4ca1b4c915.png)

Appears that there is no proboem with other smaller types.

Thanks

**Comment by x13pixels** [comment]
Fixed.
