### ISSUE TITLE
UI does not scale on HiDPI monitors

### ISSUE THREAD

**Issue by Bulmanator** [x13pixels/remedybg-issues#206]
I have a 4K screen and the UI elements for Remedy show up really small when using it on this screen, even though I have set the Windows scaling properties to 200%.

An example can be seen in the pictures below:
**1080p**
![1080](https://user-images.githubusercontent.com/8584482/105499874-04416880-5cba-11eb-8bf2-f19053db598a.png)

**4K**
![3840](https://user-images.githubusercontent.com/8584482/105499884-07d4ef80-5cba-11eb-8d99-02434362e1ef.png)

While the menu controls look the same size in the pictures. The title bar is much bigger on the 4K picture as it is being scaled up by Windows where as the menu is not so it appears much smaller.

**Comment by x13pixels** [comment]
[03.5.0] UI will now be scaled automatically based on the DPI.
