### ISSUE TITLE
(Minor feature request) Buttons for debugger control?

### ISSUE THREAD

**Issue by sonictk** [x13pixels/remedybg-issues#208]
Hi:

(Hopefully a minor and easy request) Would it be possible to have a panel with buttons for the debugger controls on them? (i.e. Pause/Resume/break, restart, step in/out/over, etc.) I know they are accessible from the menubar, but that requires going into there each time I want to trigger it (I know it sounds odd, but sometimes I want to be able to just click on the action instead of having to use the hotkey). It would be OK even if they were literally buttons with text labels on them, as long as maybe I could dock it and trigger the debugger actions from them.

Again, I might be misunderstanding how big of a deal this would be to implement, so this is definitely on the "nice-to-have" list.

**Comment by x13pixels** [comment]
![image](https://user-images.githubusercontent.com/3690363/109404653-1a37ee00-7936-11eb-8c77-e5fda023bd58.png)

I made a stab at this. However, my crappy programmer art is much too embarrassing to live with (see exhibit A). I will try some other ideas or resort to text as suggested :)

**Comment by x13pixels** [comment]
![image](https://user-images.githubusercontent.com/3690363/110488809-d757e200-80bc-11eb-90f5-c3b6ac20d061.png)
![image](https://user-images.githubusercontent.com/3690363/110488796-d3c45b00-80bc-11eb-91e0-55120e401899.png)

[3.5.0] Added optional toolbar for controlling debugger.
