### ISSUE TITLE
Show location for NULL function pointer call

### ISSUE THREAD

**Issue by leon-bckl** [x13pixels/remedybg-issues#210]
Encountered this today when I accidentally called a function pointer that was NULL. Remedy gives the following error but does not show the location where it happened:
`Exception thrown at 0x0000000000000000: 0xC0000005: User-mode data execution prevention (DEP) violation at 0x0000000000000000`

Expected behavior would be for it to show the location in the code like for other NULL-pointer access errors.

**Comment by x13pixels** [comment]
[0.3.5.0] Properly unwind stack in the case that null function pointer called.
