### ISSUE TITLE
MSVC/Clang difference regarding static local variables

### ISSUE THREAD

**Issue by Feacur** [x13pixels/remedybg-issues#213]
Heya, @x13pixels! Evidently, there's some divergence between MSVC's and Clang's static variables. That's not a bug at your side, however! Clang prefixes such variables with their scope name or something (I'm not entirely sure if this is solvable with compiler/linker flags)

just for the sake of it, build scripts etc.: https://github.com/Feacur/game_prototype/tree/master/project

Somewhat related to: https://github.com/x13pixels/remedybg-issues/issues/201

# MSVC #
works:
![image](https://user-images.githubusercontent.com/1132582/114948153-254bcc80-9e57-11eb-9426-c3a8741f4aa7.png)
... and its PDB
![image](https://user-images.githubusercontent.com/1132582/114949093-f8001e00-9e58-11eb-86bd-b75c57f05f6c.png)

# Clang #
doesn't work:
![image](https://user-images.githubusercontent.com/1132582/114948290-5e843c80-9e57-11eb-90d2-560cf3065a88.png)
... works if using full names:
![image](https://user-images.githubusercontent.com/1132582/114948630-10bc0400-9e58-11eb-8bf7-9e0edb05015e.png)
... and its PDB
![image](https://user-images.githubusercontent.com/1132582/114948707-38ab6780-9e58-11eb-9966-01969911d95c.png)

P.S.: thank you for the awesome debugger, it works like a charm and convenient UX-wise =)

**Comment by x13pixels** [comment]
Appreciate the heads up! I believe this can covered by automatically prefixing an expression with the appropriate namespace(s) when necessary.

**Comment by mmozeiko** [comment]
This was broken in llvm pdb writer since clang v11 release with following commit/review:
https://github.com/llvm/llvm-project/commit/721ea5b380b8c8304d24e14b9164660604b93032
https://reviews.llvm.org/D79028

It is broken for any debugger - VS or Remedy, as debug info in pdb is wrong. Discussion on discord where we found it: https://discord.com/channels/239737791225790464/621841127661764622/829903678953095208

**Comment by x13pixels** [comment]
The debug information for inline static vars was fixed in LLVM 16.X (broken between LLVM 11.X and 15.X, inclusive). Closing this issue.

**Comment by mmozeiko** [comment]
Oh, wow this is actually fixed in clang. Pretty cool!
