### ISSUE TITLE
CMake Clang support

### ISSUE THREAD

**Issue by atticus5** [x13pixels/remedybg-issues#215]
This is are the steps for compiling/building my app (mingw clang + make):
```
cmake.exe -DCMAKE_C_COMPILER=C:/msys64/mingw64/bin/clang.exe -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -G "MinGW Makefiles" -Bbuild -DCMAKE_BUILD_TYPE=Debug
mingw32-make.exe -C build
```

Is there to make this compatible with remedybg?

**Comment by x13pixels** [comment]
From Discord #remedybg channel

Atticus: For the record, if you are using cmake with clang.exe as compiler make sure you do the followings:
```
add_compile_options(-g -gcodeview)
target_link_libraries(${PROJECT_NAME} -fuse-ld=lld -Wl,/debug,/pdb:name.pdb)
```

Martins: you can use compile options for target too, just like linker ones: `target_compile_options(${PROJECT_NAME} PRIVATE -g -gcodeview)`
