### ISSUE TITLE
Allow mouse scroll to scroll visible tabs in the tab bar

### ISSUE THREAD

**Issue by sonictk** [x13pixels/remedybg-issues#216]
Minor feature request; if it was possible to allow for mouse scroll to scroll the display of the tabs when there are too many to display in the top tab bar, that would be nice. There's a lot of features already (drop down arrow, `ctrl(+shift)-tab` navigation, but usually it's nice to be able to be scroll with the mouse wheel and go left/right in the tabs view. (However not sure if ImGui already has this built-in though)

**Comment by x13pixels** [comment]
0.3.9.0: upgraded to latest Dear ImGui which has shift+scroll wheel built-in for this.
