### ISSUE TITLE
"Send to Memory window" problem on dereferenced/"expanded" pointers in watch view

### ISSUE THREAD

**Issue by JensWallgren** [x13pixels/remedybg-issues#219]
I believe this issue is reproducable on any pointer variable in the watch window.
The string generated for the 'Address' field of the Memory window is invalid.

![image](https://user-images.githubusercontent.com/29680165/127565227-50de4502-b86c-4163-94ec-9e04334f609b.png)

![image](https://user-images.githubusercontent.com/29680165/127565255-4f6ca89d-4507-43df-9791-bfbbeeb63caf.png)

**Comment by x13pixels** [comment]
Fixed expression generated for Add Watch / Send to Memory Window for dereferenced pointers.
