### ISSUE TITLE
0.3.5.4 watch window bug: typing a value and hitting enter stops autofocusing the next entry when the watch window is around full

### ISSUE THREAD

**Issue by boulware** [x13pixels/remedybg-issues#224]
Repro:
1) Open Remedy
2) Open a watch window
3) Select the first (empty) entry in the watch window
4) Type anything, press enter, and repeat.
5) Once you've repeated enough times that the watch window starts to get full, after hitting enter on an entry, the next entry will not automatically focus, so typing doesn't begin filling in the next watch entry.

Video: https://youtu.be/35-B7oKirIk

**Comment by x13pixels** [comment]
Fixed in upcoming 0.3.6.0.
