### ISSUE TITLE
Can't start typing an expression with "$"

### ISSUE THREAD

**Issue by seventh-chord** [x13pixels/remedybg-issues#225]
When focused on a row in the watch window I can start typing and the white textbox-thing comes up and accepts input.
This doesn't work if I start typing with a $ or another third-layer key on my keyboard.
I can type these keys just fine once I'm in the textbox thing (e.g. if I first type another letter to get it to appear).
I assume this is related to me being on an european keyboard layout where I press altgr+4 to type $.

**Comment by x13pixels** [comment]
[0.3.6.1] AltGR+[^A-Z] can now be used to initiate an edit in the watch window.
