### ISSUE TITLE
Feature request: Drag breakpoints to change their line number

### ISSUE THREAD

**Issue by pmttavara** [x13pixels/remedybg-issues#226]
Sometimes I write a conditional breakpoint and don't want to rewrite the condition again to move the line number, but i don't think i can edit the line number in the breakpoint properties or drag the breakpoint around. I would appreciate either a line edit ability or breakpoint drag-and-drop to new lines. (Or both! 😅)

**Comment by x13pixels** [comment]
0.3.8.0. Can now edit line number in the edit breakpoint dialog.
