### ISSUE TITLE
Command and Working Directory selectors not pointing to the correct directory

### ISSUE THREAD

**Issue by ghost** [x13pixels/remedybg-issues#227]
I've just purchased remedybg and noticed this behaviour. Not sure if it is intended or not, but I found it a bit confusing.

I'm running version 0.3.6.2.

## Expected behaviour

When I start remedybg on an executable, I expected both the Command and Working Directory fields to be populated with the directory where the binary is located. When I try to change directories, I expect the pop up window to open the directory listed in those fields.

## Actual behaviour

When I click the button to change the directories, the Windows pop-up window doesn't open in the same directory listed in the UI. It opens where the source files are located (e.g., src directory).

## Screenshots

Here the command and working directories are correctly set to where the binary is located: `p:\build`

![first](https://user-images.githubusercontent.com/90465881/135752221-1d8a9351-1dcc-42ec-a636-1bbfce2e5cc9.PNG)

When I click either button to choose a  directory, the pop-up opens at the source code location: `p:\blaise\src`.

![second](https://user-images.githubusercontent.com/90465881/135752223-de0354f6-3d2a-4ae9-8291-37945f6af25c.PNG)

**Comment by x13pixels** [comment]
Fixed in 0.3.9.9: Initial directory used in file open dialog for command/working directory is now based on the current command, rather than use the application's last visited directory.
