### ISSUE TITLE
Support Windows style paths

### ISSUE THREAD

**Issue by vamolessa** [x13pixels/remedybg-issues#231]
Support launching remedybg from cli using windows style paths.
That is, paths which use `\` as a separator.

**Comment by x13pixels** [comment]
I might be missing something. This appears to work as expected for me. Could you please paste in an example?

**Comment by vamolessa** [comment]
Oh, sorry!
That was actually my wonky shell's fault. It interpreted the `\` as escapes even without quotes.
When testing with windows cmd, it worked as intended.
Thanks!
