### ISSUE TITLE
0.3.6.4 Bug: enum class with explicit underlying type of unsigned char is interpreted as having sizeof(Enum) = 4 in watch window

### ISSUE THREAD

**Issue by boulware** [x13pixels/remedybg-issues#232]
```#include "stdio.h"
enum class Fruit : unsigned char
{
    Apple,
    Banana,
    Cranberry,
};

int main()
{
    Fruit fruits[] = {Fruit::Apple, Fruit::Banana, Fruit::Cranberry};
    printf("sizeof(Fruit) = %zu", sizeof(Fruit));
}
```
This prints `sizeof(Fruit) = 1`, but the RBG watch window shows `sizeof(Fruit) = 4`. The comma array display syntax also does not work correctly:

![image](https://user-images.githubusercontent.com/4677407/160259876-08c92c24-c882-486c-87eb-c871a4844186.png)

**Comment by x13pixels** [comment]
[0.3.7.0] Fixed computation of array element addresses for non-int sized enums.
