### ISSUE TITLE
Feature request: copy callstack

### ISSUE THREAD

**Issue by sonictk** [x13pixels/remedybg-issues#233]
This would be really helpful for sharing stack traces with other programmers in general: right now I can't just copy rows of text from the Call stack window; I have to take a screenshot and send it over to them. It would be much nicer if I could just Ctrl-C from it like in other places in the debugger.

(There's a bunch of places where in general it would be nice to be able to Ctrl-C from them (especially in the Watch window, where not every cell can have its value copied to the clipboard even as text), but this one is by far the most useful IMHO.)

**Comment by x13pixels** [comment]
[0.3.7.0] Added Copy menu / Ctrl+C to call stack window.
