### ISSUE TITLE
Disable breakpoint directly in context menu

### ISSUE THREAD

**Issue by sonictk** [x13pixels/remedybg-issues#235]
It would be nice to be able to disable breakpoints directly through some shortcut, even if it is in the right-click context menu. This way it wouldn't require hunting in the breakpoints window for the specific breakpoint that you're trying to disable.

**Comment by x13pixels** [comment]
Ctrl+F9 _should_ work. I'll double-check this. I can also add this to the context menu for additional documentation.

**Comment by sonictk** [comment]
> Ctrl+F9 should work.

Omg, it does! I missed that in the `README`, whoops! Lifesaver. 

> I can also add this to the context menu for additional documentation.

Yes, please and thank you :)

**Comment by x13pixels** [comment]
[0.3.7.1] Added bp context-menu items "Enable Breakpoint (Ctrl+F9)" / "Disable Breakpoint (Ctrl+F9)"
