### ISSUE TITLE
3.7.0 Default array drop down not working

### ISSUE THREAD

**Issue by Nates3** [x13pixels/remedybg-issues#236]
In the watch window for version 0.3.7.0, the default drop down for arrays doesn't work for me. 

0.3.7.0 doesn't work
![REM370](https://user-images.githubusercontent.com/32080038/162350713-2fdefcab-80b9-4f39-aa1c-92f35e4e4e8b.png)

0.3.6.4 works
![REM364](https://user-images.githubusercontent.com/32080038/162349926-dcdc8d80-b881-455f-a3e8-8ac8ad3c292d.png)

**Comment by x13pixels** [comment]
[0.3.7.1] Fixed array evaluation that was inadvertently broke during dev of new 0.3.7.0.
