### ISSUE TITLE
"Break when value changes" context menu convenience feature (data breakpoint)

### ISSUE THREAD

**Issue by sonictk** [x13pixels/remedybg-issues#237]
This might seem really frivolous, but it would be _really_ convenient to have a feature where you can add a data breakpoint easily similar to VS where it defaults to adding a data breakpoint with the correct size (i.e. `int` adds a data breakpoint that watches 4 bytes, any pointer watches 8 bytes etc.). I can't tell how many times I just want to catch issues like these during debugging and end up going to VS just to get the expression to paste in RemedyBG.

![image](https://user-images.githubusercontent.com/2504199/163342277-4f67ef6d-7577-4877-b6df-05d01591d3d8.png)

**Comment by x13pixels** [comment]
Added in 0.3.8.2. Missed closing this issue.
