### ISSUE TITLE
Unable to dock two or more array table views

### ISSUE THREAD

**Issue by sir-pinecone** [x13pixels/remedybg-issues#238]
I have a few expressions in the watch window that format arrays as a table. If I click the magnifying glass on one then it correctly docks the table outside of the watch window. If I then do the same on a different expression, it appears to be drawn over the other docked view and the text is quickly flickering. I'm unable to see the first view's data.

This is on version 0.3.7.1

**Comment by x13pixels** [comment]
[0.3.8.0] Fixed computation of hash used to disambiguate expressions and their associated windows.

**Comment by sir-pinecone** [comment]
Thanks for the quick turnaround! You rock!
