### ISSUE TITLE
Sometimes Window/GUI doesn't display if imgui180.ini file exists in %AppData% directory

### ISSUE THREAD

**Issue by Amaranthos** [x13pixels/remedybg-issues#240]
RemedyBG version: 0.3.7.1
Windows 11 Pro version: 21H2 osbuild: 22000.675

Not 100% reproducible but occasionally happens.
The process launches but no window displays if imgui180.ini file exists `%AppData%/Roaming/remedybg/`
Deleting the file and relaunching solves the problem.

ini contents
```
[Window][Threads]
Pos=0,29
Size=6,3
Collapsed=0
DockId=0x00000005,0

[Window][Modules]
Pos=0,29
Size=6,3
Collapsed=0
DockId=0x00000005,1

[Window][Watch 1]
Pos=17,20
Size=15,12
Collapsed=0
DockId=0x00000008,0

[Window][Watch 2]
Collapsed=0
DockId=0x00000006

[Window][Watch 3]
Collapsed=0
DockId=0x00000006

[Window][Watch 4]
Collapsed=0
DockId=0x00000006

[Window][Watch 5]
Collapsed=0
DockId=0x00000006

[Window][Watch 6]
Collapsed=0
DockId=0x00000006

[Window][Watch 7]
Collapsed=0
DockId=0x00000006

[Window][Watch 8]
Collapsed=0
DockId=0x00000006

[Window][Memory 1]
Collapsed=0
DockId=0x00000006

[Window][Memory 2]
Collapsed=0
DockId=0x00000006

[Window][Memory 3]
Collapsed=0
DockId=0x00000006

[Window][Memory 4]
Collapsed=0
DockId=0x00000006

[Window][Registers]
Collapsed=0
DockId=0x00000005

[Window][Call Stack]
Pos=8,29
Size=7,3
Collapsed=0
DockId=0x00000006,0

[Window][Breakpoints]
Pos=8,29
Size=7,3
Collapsed=0
DockId=0x00000006,1

[Window][Output]
Pos=0,24
Size=7,3
Collapsed=0
DockId=0x0000000A,0

[Window][Disassembly]
Pos=9,20
Size=6,7
Collapsed=0
DockId=0x00000004,0

[Window][DockSpace]
Pos=0,0
Size=32,32
Collapsed=0

[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][###000]
Pos=0,20
Size=7,2
Collapsed=0
DockId=0x00000009,0

[Table][0x15927E8D,8]
RefScale=14
Column 0  Width=9
Column 1  Width=93
Column 2  Width=633
Column 3  Width=178
Column 4  Width=338
Column 5  Width=448
Column 6  Width=102
Column 7  Width=152

[Table][0xDD84BC85,4]
RefScale=14
Column 0  Width=9
Column 1  Width=178
Column 2  Width=439
Column 3  Width=102

[Docking][Data]
DockSpace         ID=0x42AD2D21 Window=0x9A404470 Pos=0,20 Size=32,12 Split=X
  DockNode        ID=0x00000007 Parent=0x42AD2D21 SizeRef=973,1390 Split=Y
    DockNode      ID=0x00000001 Parent=0x00000007 SizeRef=3824,1033 Split=X
      DockNode    ID=0x00000003 Parent=0x00000001 SizeRef=1911,661 Split=Y
        DockNode  ID=0x00000009 Parent=0x00000003 SizeRef=1280,698 CentralNode=1 Selected=0xD9E860F0
        DockNode  ID=0x0000000A Parent=0x00000003 SizeRef=1280,333 Selected=0xCB7211A8
      DockNode    ID=0x00000004 Parent=0x00000001 SizeRef=1911,661 Selected=0x96E13B49
    DockNode      ID=0x00000002 Parent=0x00000007 SizeRef=3824,355 Split=X
      DockNode    ID=0x00000005 Parent=0x00000002 SizeRef=319,357 Selected=0xA0330441
      DockNode    ID=0x00000006 Parent=0x00000002 SizeRef=652,357 Selected=0x57AA7412
  DockNode        ID=0x00000008 Parent=0x42AD2D21 SizeRef=1584,1390 Selected=0x1FE9745A

[RemedyBG][WindowPos]
x=2552
y=-32768
w=2576
h=1449
M=0

[RemedyBG][Style]
UiFontName=C:\WINDOWS\Fonts\lucon.ttf
UiFontSizePx=14
UiStyle=1
ScrollbarSizePx=14
ShowWindowFocus=1
ShowToolbar=0
TextFontName=C:\WINDOWS\Fonts\lucon.ttf
TextFontSizePx=14
TextForegroundClr=#DCDCDC
TextBackgroundClr=#3F3F3F
TextTabSpacing=4
EvaluateOnHover=1
TooltipDelayMs=400

[RemedyBG][RecentFiles]
C:\Projects\handmade\handmade.rdbg

[RemedyBG][Other]
AutoSaveEnabled=0
OpenLastSessionOnStartup=1
AutoClearOutputWindow=0
ShowModuleLoad=1
ShowModuleUnload=1
ShowThreadExit=1
ShowProcessExit=1

[RemedyBG][Layout]
O=1

[RemedyBG][ThreadsWindow]
ShowWnd=1
ShowName=1
ShowModule=1
ShowFunctionName=1
ShowCallingFunctionName=1
ShowAddress=1
ShowPriority=1

[RemedyBG][ModulesWindow]
ShowWnd=1
ShowPath=1
ShowAddress=1
ShowSymbolFile=1
ShowStatus=1

[RemedyBG][Watch-0]
ShowWnd=1
ShowType=1
ShowComment=0
Hexadecimal=0
ColumnMaj=0

[RemedyBG][BreakpointsWindow]
ShowWnd=1

[RemedyBG][CallstackWindow]
ShowWnd=1
ShowModuleName=1
ShowAddress=1
Verbosity=1

[RemedyBG][Memory-0]
ShowWnd=0
NumColumns=32
ShowDataPreview=0
ShowHexII=0
ShowAscii=1
GreyOutZeros=1
UpperCaseHex=1
ReadOnly=0

[RemedyBG][RegistersWindow]
ShowWnd=0
ShowRIP=1
ShowGeneralPurposeRegs=1
ShowEFLAGS=1
ShowSegmentRegs=0
ShowSSE=0
ShowAVX=0
ShowAVX512=0

[RemedyBG][DisassemblyWindow]
ShowWnd=1
ShowCodeBytes=1
ShowAddress=1

[RemedyBG][OutputWindow]
ShowWnd=1

[RemedyBG][LayoutOther]
StatusTextPosTop=1
StatusTextShowPID=1

[RemedyBG][Watch-1]
ShowWnd=0
ShowType=1
ShowComment=0
Hexadecimal=0
ColumnMaj=0

[RemedyBG][Watch-2]
ShowWnd=0
ShowType=1
ShowComment=0
Hexadecimal=0
ColumnMaj=0

[RemedyBG][Watch-3]
ShowWnd=0
ShowType=1
ShowComment=0
Hexadecimal=0
ColumnMaj=0

[RemedyBG][Watch-4]
ShowWnd=0
ShowType=1
ShowComment=0
Hexadecimal=0
ColumnMaj=0

[RemedyBG][Watch-5]
ShowWnd=0
ShowType=1
ShowComment=0
Hexadecimal=0
ColumnMaj=0

[RemedyBG][Watch-6]
ShowWnd=0
ShowType=1
ShowComment=0
Hexadecimal=0
ColumnMaj=0

[RemedyBG][Watch-7]
ShowWnd=0
ShowType=1
ShowComment=0
Hexadecimal=0
ColumnMaj=0

[RemedyBG][Memory-1]
ShowWnd=0
NumColumns=32
ShowDataPreview=0
ShowHexII=0
ShowAscii=1
GreyOutZeros=1
UpperCaseHex=1
ReadOnly=0

[RemedyBG][Memory-2]
ShowWnd=0
NumColumns=32
ShowDataPreview=0
ShowHexII=0
ShowAscii=1
GreyOutZeros=1
UpperCaseHex=1
ReadOnly=0

[RemedyBG][Memory-3]
ShowWnd=0
NumColumns=32
ShowDataPreview=0
ShowHexII=0
ShowAscii=1
GreyOutZeros=1
UpperCaseHex=1
ReadOnly=0


```

**Comment by zxubian** [comment]
Same issue here! Glad to have found a workaround.
<details>
<summary>ini contents</summary>

[Window][Threads]
Pos=0,29
Size=15,3
Collapsed=0
DockId=0x00000005,0

[Window][Modules]
Pos=0,29
Size=15,3
Collapsed=0
DockId=0x00000005,1

[Window][Watch 1]
Pos=17,29
Size=15,3
Collapsed=0
DockId=0x00000006,0

[Window][Watch 2]
Collapsed=0
DockId=0x00000006

[Window][Watch 3]
Collapsed=0
DockId=0x00000006

[Window][Watch 4]
Collapsed=0
DockId=0x00000006

[Window][Watch 5]
Collapsed=0
DockId=0x00000006

[Window][Watch 6]
Collapsed=0
DockId=0x00000006

[Window][Watch 7]
Collapsed=0
DockId=0x00000006

[Window][Watch 8]
Collapsed=0
DockId=0x00000006

[Window][Memory 1]
Collapsed=0
DockId=0x00000006

[Window][Memory 2]
Collapsed=0
DockId=0x00000006

[Window][Memory 3]
Collapsed=0
DockId=0x00000006

[Window][Memory 4]
Collapsed=0
DockId=0x00000006

[Window][Registers]
Collapsed=0
DockId=0x00000005

[Window][Call Stack]
Pos=17,29
Size=15,3
Collapsed=0
DockId=0x00000006,1

[Window][Breakpoints]
Pos=17,29
Size=15,3
Collapsed=0
DockId=0x00000006,2

[Window][Output]
Pos=17,29
Size=15,3
Collapsed=0
DockId=0x00000006,3

[Window][Disassembly]
Collapsed=0
DockId=0x00000004

[Window][DockSpace]
Pos=0,0
Size=32,32
Collapsed=0

[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][###003]
Pos=0,20
Size=32,7
Collapsed=0
DockId=0x00000003,0

[Window][###002]
Pos=0,20
Size=32,7
Collapsed=0
DockId=0x00000003,1

[Window][###001]
Pos=0,20
Size=32,7
Collapsed=0
DockId=0x00000003,2

[Window][###000]
Pos=0,20
Size=32,7
Collapsed=0
DockId=0x00000003,3

[Window][###wndadbp]
Pos=208,468
Size=510,112
Collapsed=0

[Table][0x15927E8D,8]
RefScale=14
Column 0  Width=9
Column 1  Width=93
Column 2  Width=169
Column 3  Width=152
Column 4  Width=178
Column 5  Width=186
Column 6  Width=102
Column 7  Width=152

[Table][0xDD84BC85,4]
RefScale=14
Column 0  Width=9
Column 1  Width=152
Column 2  Width=591
Column 3  Width=102

[Table][0x4CD8709F,3]
Column 0  Weight=0.2531
Column 1  Weight=0.6461
Column 2  Weight=0.1008

[Table][0x433F954A,2]
RefScale=14
Column 0  Width=9
Column 1  Weight=1.0000

[Docking][Data]
DockSpace     ID=0x42AD2D21 Window=0x9A404470 Pos=0,20 Size=32,12 Split=Y
  DockNode    ID=0x00000001 Parent=0x42AD2D21 SizeRef=1378,690 Split=X
    DockNode  ID=0x00000003 Parent=0x00000001 SizeRef=688,486 CentralNode=1 Selected=0xD9E860F0
    DockNode  ID=0x00000004 Parent=0x00000001 SizeRef=688,486
  DockNode    ID=0x00000002 Parent=0x42AD2D21 SizeRef=1378,345 Split=X
    DockNode  ID=0x00000005 Parent=0x00000002 SizeRef=453,262 Selected=0xA0330441
    DockNode  ID=0x00000006 Parent=0x00000002 SizeRef=923,262 Selected=0x1FE9745A

[RemedyBG][WindowPos]
x=54
y=-32768
w=1874
h=1096
M=0

[RemedyBG][Style]
UiFontName=C:\Windows\Fonts\lucon.ttf
UiFontSizePx=14
UiStyle=1
ScrollbarSizePx=14
ShowWindowFocus=1
ShowToolbar=0
TextFontName=C:\Windows\Fonts\lucon.ttf
TextFontSizePx=15
TextForegroundClr=#DCDCDC
TextBackgroundClr=#3F3F3F
TextTabSpacing=4
EvaluateOnHover=1
TooltipDelayMs=400

[RemedyBG][RecentFiles]
C:\Andy\Study\handmade\debugging_session.rdbg

[RemedyBG][Other]
AutoSaveEnabled=0
OpenLastSessionOnStartup=1
AutoClearOutputWindow=0
ShowModuleLoad=1
ShowModuleUnload=1
ShowThreadExit=1
ShowProcessExit=1

[RemedyBG][Layout]
O=1

[RemedyBG][ThreadsWindow]
ShowWnd=1
ShowName=1
ShowModule=1
ShowFunctionName=1
ShowCallingFunctionName=1
ShowAddress=1
ShowPriority=1

[RemedyBG][ModulesWindow]
ShowWnd=1
ShowPath=1
ShowAddress=1
ShowSymbolFile=1
ShowStatus=1

[RemedyBG][Watch-0]
ShowWnd=1
ShowType=1
ShowComment=0
Hexadecimal=0
ColumnMaj=0

[RemedyBG][BreakpointsWindow]
ShowWnd=1

[RemedyBG][CallstackWindow]
ShowWnd=1
ShowModuleName=1
ShowAddress=1
Verbosity=1

[RemedyBG][Memory-0]
ShowWnd=0
NumColumns=32
ShowDataPreview=0
ShowHexII=0
ShowAscii=1
GreyOutZeros=1
UpperCaseHex=1
ReadOnly=0

[RemedyBG][RegistersWindow]
ShowWnd=0
ShowRIP=1
ShowGeneralPurposeRegs=1
ShowEFLAGS=1
ShowSegmentRegs=0
ShowSSE=0
ShowAVX=0
ShowAVX512=0

[RemedyBG][DisassemblyWindow]
ShowWnd=0
ShowCodeBytes=1
ShowAddress=1

[RemedyBG][OutputWindow]
ShowWnd=1

[RemedyBG][LayoutOther]
StatusTextPosTop=1
StatusTextShowPID=1

[RemedyBG][Watch-1]
ShowWnd=0
ShowType=1
ShowComment=0
Hexadecimal=0
ColumnMaj=0

[RemedyBG][Watch-2]
ShowWnd=0
ShowType=1
ShowComment=0
Hexadecimal=0
ColumnMaj=0

[RemedyBG][Watch-3]
ShowWnd=0
ShowType=1
ShowComment=0
Hexadecimal=0
ColumnMaj=0

[RemedyBG][Watch-4]
ShowWnd=0
ShowType=1
ShowComment=0
Hexadecimal=0
ColumnMaj=0

[RemedyBG][Watch-5]
ShowWnd=0
ShowType=1
ShowComment=0
Hexadecimal=0
ColumnMaj=0

[RemedyBG][Watch-6]
ShowWnd=0
ShowType=1
ShowComment=0
Hexadecimal=0
ColumnMaj=0

[RemedyBG][Watch-7]
ShowWnd=0
ShowType=1
ShowComment=0
Hexadecimal=0
ColumnMaj=0

[RemedyBG][Memory-1]
ShowWnd=0
NumColumns=32
ShowDataPreview=0
ShowHexII=0
ShowAscii=1
GreyOutZeros=1
UpperCaseHex=1
ReadOnly=0

[RemedyBG][Memory-2]
ShowWnd=0
NumColumns=32
ShowDataPreview=0
ShowHexII=0
ShowAscii=1
GreyOutZeros=1
UpperCaseHex=1
ReadOnly=0

[RemedyBG][Memory-3]
ShowWnd=0
NumColumns=32
ShowDataPreview=0
ShowHexII=0
ShowAscii=1
GreyOutZeros=1
UpperCaseHex=1
ReadOnly=0

</details>

**Comment by x13pixels** [comment]
[0.3.8.0] Fixed a case where values in `[RemedyBG][WindowPos]` could place the window offscreen.
