### ISSUE TITLE
Show template parameters' real types in watch window

### ISSUE THREAD

**Issue by JustSlavic** [x13pixels/remedybg-issues#242]
I'm not sure if this is even possible, but it would be nice to see what types are in template parameters. I can see them in call stack window, but it quickly gets really messy and often doesn't even fit in the width of my 2k monitor. Watch window does not recognize it and mouse hover does nothing too. Maybe if watch window could recognize them, we even could use it in expressions like `(T *) memory, 3` (as an array T[3]), might be useful.

![image](https://user-images.githubusercontent.com/26839955/169918609-85038543-5fc8-4205-b679-c23505f8c7fb.png)

Templates are real pain for me, because it's really hard to see what's going on, and such inspection would really help. But if it's not possible, so be it. 

P.S. Thank you for such a great tool, I really enjoy using it!

**Comment by x13pixels** [comment]
Double-checked and the MSVC compiler does not emit source template parameters in the symbol file after they have been monomorphized.
