### ISSUE TITLE
Detatch from process does not work

### ISSUE THREAD

**Issue by JustSlavic** [x13pixels/remedybg-issues#243]
I have the simplest window application which does almost nothing: 

```c++
int WinMain(HINSTANCE Instance, HINSTANCE PrevInstance, LPSTR CommandLine, Int32 ShowCode))
{
    // RegisterClassA call
    // AdjustWindowRect call
    // CreateWindowExA call

    Running = true;
    while (Running)
    {
        MSG Message;
        while (PeekMessageA(&Message, 0, 0, 0, PM_REMOVE)) {
            if (Message.message == WM_QUIT) Running = false;
            TranslateMessage(&Message);
            DispatchMessageA(&Message);
        }

        Sleep(30);
    }
    
    return 0;
}
```

I attach to it with RemedyBG, it stops the execution. Press F5. 
Press `Control->Detatch` does nothing, status bar says `Program is running because F5 was hit`.

So next, if I press `Control->Break` does nothing, but status bar now says `Program is running (waiting for process to halt from Control|Break)`.
But if I hit breakpoint... it just breaks the debugger. It starts popping to the front of all of other windows, breakpoint line turns red and status bar switching between messages like crazy. Messages are:

![image](https://user-images.githubusercontent.com/26839955/170792325-a7bc2174-f818-4291-a0d0-7670826f0925.png)

and

![image](https://user-images.githubusercontent.com/26839955/170792411-9640dc0b-4a61-4ce4-a023-db9c53989e98.png)

It reproduces with all of my executables with opened windows. 
Upd: It also reproduces when there's just an infinite loop (so I can attach to process) and no window opened.

**Comment by x13pixels** [comment]
Fixed in 0.3.8.0
