### ISSUE TITLE
Feature Request: Configurable External Tools

### ISSUE THREAD

**Issue by sdwe** [x13pixels/remedybg-issues#245]
I'd appreciate a facility similar to 'Tools > External Tools...' in VS:
https://docs.microsoft.com/en-us/visualstudio/ide/managing-external-tools

My main use case would be opening the active source file at its current location in an external editor.

**Comment by x13pixels** [comment]
This will be available in the next release, 0.4.0.5

**Comment by sdwe** [comment]
Great, thank you so much! :thumbsup:
