### ISSUE TITLE
Cannot load pdb files larger than 4GiB

### ISSUE THREAD

**Issue by sonictk** [x13pixels/remedybg-issues#249]
It looks like RemedyBG will fail to load PDBs that are larger than 4 GiB, which causes no symbols to be available when debugging processes that use that PDB file. This is especially of use when debugging executables like Unreal Engine which easily hit the limit.

https://developercommunity.visualstudio.com/t/pdb-limit-of-4-gib-is-likely-to-be-a-problem-in-a/904784

I wonder what it would take to support this? I couldn't find much information about the PDB format other than what is available at: https://github.com/microsoft/microsoft-pdb and how `/pdbpagesize` was implemented. It looks like later versions of `msdia140.dll` were updated to support this anecdotally, but I am assuming RemedyBG doesn't use that.

**Comment by x13pixels** [comment]
There is currently a check to ensure the PDB size is one of 1K, 2K, or 4K (derived from the microsoft-pdb repo). Will relax the constraint to allow for 8K, 16K, and 32K pages as well. Thanks!

**Comment by x13pixels** [comment]
0.3.8.0 Added support for 8K, 16K, and 32K PDB page sizes.
