### ISSUE TITLE
Idea: Publish as an extension on the visual studio marketplace?

### ISSUE THREAD

**Issue by AndrewJDR** [x13pixels/remedybg-issues#251]
I'm not even a visual studio user, so this isn't something I want, it's just a potential marketing idea to consider... perhaps publishing remedybg on the [visual studio marketplace](https://marketplace.visualstudio.com/) would help raise exposure, even if it's just a glorified "Launch remedybg from VS" button. No idea what's involved in publishing something on their marketplace, or if it's even a good idea. Just throwing it out there in case it hadn't been considered.

**Comment by x13pixels** [comment]
Thanks. Noting the suggestion and closing the issue.
