### ISSUE TITLE
Bug: copy values for complex datatypes

### ISSUE THREAD

**Issue by dstasio** [x13pixels/remedybg-issues#253]
When displaying the value for a struct or a union, clicking 'Copy Value' on its inline representation does nothing. 
It would be useful to be able to copy what we see in the "Value" column, however messy it is.

For example, with the following type:
```cpp
union v3
{
    struct { r32 x, y, z; };
    r32    row[3];
    v2     xy;
};
```

![image](https://user-images.githubusercontent.com/22714616/177967947-9460cbb7-c8fd-413a-af08-df4c021d83d8.png)

**Comment by x13pixels** [comment]
[0.3.8.0] Fixed handling of copy/copy value for struct/union types.
