### ISSUE TITLE
Call stack view unresponsive without 'Module Name' active

### ISSUE THREAD

**Issue by Kipt** [x13pixels/remedybg-issues#258]
Seems "Call Stack" view becomes unresponsive if you hide module name. Haven't made a minimal repro case but it's probably easy to reproduce (I can provide one if not).

Steps to reproduce:
1. From Call Stack view, right-click and remove "Module Name" option. (Reproduced using "Minimal" settings)
2. Set a breakpoint.
3. Run program and hit breakpoint.
4. Single click any row in the Call Stack view.
5. Double click any row in the Call Stack view.

Expected result:
- With single click, the row should be selected.
- With double click, call stack indicator (right arrow) and source code text view should move to double clicked frame.

Actual result:
- Call Stack view is unresponsive and clicking it does nothing, although other views are responding to input.

Notes:
Adding "Module Name" to view makes it responsive again.

RemedyBG version: 0.3.7.1 (also reproduced on 0.3.6.1)

**Comment by x13pixels** [comment]
Fixed in 0.3.8.0
