### ISSUE TITLE
Step Into (line) is not behaving as intended

### ISSUE THREAD

**Issue by septag** [x13pixels/remedybg-issues#259]
Hi
RemedyBG version: 0.3.7.1
Perhaps I'm doing something wrong, but Step-into (line) F11, is not acting as it should for me.
For instance, if I put a breakpoint on a line, and step-into a function, after that, everything switches to step by instruction instead of line, even F10 (Step Over line). This behavior will continue until I "Continue (F5)" again.
So basically after the first Step into function, every other step changes to instruction mode.

**Comment by McKay42** [comment]
> F10                  Step Over (Line); when disassembly window is active, this behaves as Step Over (Instruction)
> F11                  Step Into (Line); when disassembly window is active, this behaves as Step In (Instruction)

Is the disassembly window focused (yellow border) when what you mentioned happens?

This has also tripped me up a few times, especially since the focus automatically changes based on context (e.g. when main returns hitting F10/F11 will force focus the disassembly window, which is correct and makes sense because of the CRT etc., but the focus doesn't reset when restarting/starting. Clicking in the source window works around this of course).

An option to always focus the source window on start/restart would be nice.

**Comment by septag** [comment]
oh! you are right.
 it actually focuses on disassembly view and that's why it switches to instruction mode.
But this happens for me every time I step-into line, it doesn't matter if I even close the disassembly view or not, it opens-up and switches to instruction anyway. so I have to constantly focus back to source window whenever I hit that.

**Comment by McKay42** [comment]
> But this happens for me every time I step-into line, it doesn't matter if I even close the disassembly view or not, it opens-up and switches to instruction anyway. so I have to constantly focus back to source window whenever I hit that.

Hm, I definitely can't reproduce this, F11 steps into functions and then automatically opens the correct source file and jumps to where the function is there. Maybe your pdb file is somehow broken?

**Comment by septag** [comment]
I'm not exactly sure about that. but I'm following the remedybg guidelines. creating full pdb (/FULLDEBUG) with no edit&continue or incremental linking.
I can also debug pretty much without any problems. I only have this focus problem, and the thing is when I refocus on the source code, it steps correctly and doesn't revert back to disassembly

**Comment by McKay43** [comment]
See https://remedybg.handmade.network/forums/t/8349-remedy_enters_dissasembly_window_when_entering_any_function_call maybe?

**Comment by McKay42** [comment]
See https://remedybg.handmade.network/forums/t/8349-remedy_enters_dissasembly_window_when_entering_any_function_call maybe?

**Comment by septag** [comment]
ah! that was it! thank you very much.

**Comment by x13pixels** [comment]
0.3.8.0: Added a comment to the README concerning the /JMC switch. Thanks.
