### ISSUE TITLE
Current directory cannot be set with command-line

### ISSUE THREAD

**Issue by septag** [x13pixels/remedybg-issues#260]
Version 0.3.7.1
README states that:
`Working Directory: the working, or current, directory to use for the target process. If this
      is not specified, then the current directory in which RemedyBG was launched will be used
      instead.`

I actually used this to quickly start sessions by running the executable from a different current directory. but in the last version, this functionality doesn't seem to be working. Running with something like:
`
c:\>remedybg projects\test.exe
`
The current directory is same as the the exe instead of root dir

**Comment by x13pixels** [comment]
Fixed in 0.3.8.0.
