### ISSUE TITLE
Feature Request: Command-line parameter to open and attach to running process (by PID)

### ISSUE THREAD

**Issue by boulware** [x13pixels/remedybg-issues#264]
Example which would be equivalent to _Session->Attach To Process..._ and selecting PID 26722:
`remedybg.exe -pid 26722`

I'd love to be able to launch RBG and attach it to the application I'm debugging even if I didn't start the process through RBG, without having to manually get the PID and select from the list in RBG.

**Comment by x13pixels** [comment]
If I'm understanding the request correctly you should be able to use the command-line option `attach-to-process-by-id`.
