### ISSUE TITLE
Named Pipe / Breakpoint notifications

### ISSUE THREAD

**Issue by Muzza** [x13pixels/remedybg-issues#265]
I've been integrating the 10x editor with remedybg using the new named pipe control, which should be an improvement on the previous command line method I was using. The reliable syncing of breakpoints between the two is one of the main goals.
Currently I can request the breakpoints from remedybg, but this requires polling to keep it in sync. 
If there was also a debug event notification when the user added/removed or enabled/disabled a breakpoint, it would make things neater.

**Comment by x13pixels** [comment]
This was added to 0.3.8.2
