### ISSUE TITLE
Text alignment with tabs incorrectly inserts 4 spaces foreach tab

### ISSUE THREAD

**Issue by kylawl** [x13pixels/remedybg-issues#266]
When rendering text with tabs, the text view always inserts 4 spaces rather than inserting sufficient white space to align up to 4 characters.

The result is that text is not aligned correctly and difficult to follow when compared to your text editor of choice.

**Comment by kylawl** [comment]
Here's a screenshot illustrating the issue. All these indents are using tabs yet they don't align

<img width="853" alt="image" src="https://user-images.githubusercontent.com/4952023/189440117-09b8bf18-ea86-46aa-a9ec-bba80dfa31f5.png">

**Comment by x13pixels** [comment]
Reworked character rendering in the text view and fixed this in the process. Thanks for reporting it (and sorry it took so long to get to).

Fix to ship in 0.3.9.7.
