### ISSUE TITLE
100% repro new crash introduced in 0.3.8.2

### ISSUE THREAD

**Issue by mlabbe** [x13pixels/remedybg-issues#267]
Upon breakpointing a function in my code Remedybg crashes.  This is occurring in one particular function, and not others.  It appears to crash before the watch window displays, but after the breakpoint is hit.

Downgrading to 0.3.8.1 causes the breakpoint to work correctly.

Rebuilding the .rdbg file does not fix the issue.

Let me know if I can provide any other information to help track it down.  Providing the codebase is unfortunately not an option, though I can provide a snippet privately.

Event Viewer:

    Fault bucket 1899521783750564721, type 4
    Event Name: APPCRASH
    Response: Not available
    Cab Id: 0
    
    Problem signature:
    P1: remedybg.exe
    P2: 0.3.8.2
    P3: 630c0b71
    P4: remedybg.exe
    P5: 0.3.8.2
    P6: 630c0b71
    P7: c0000005
    P8: 00000000000965e8
    P9: 
    P10: 
    
    Attached files:
    \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER276D.tmp.dmp
    \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2877.tmp.WERInternalMetadata.xml
    \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2898.tmp.xml
    \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER289A.tmp.csv
    \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER28C9.tmp.txt
    
    These files may be available here:
    \\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_remedybg.exe_64e6f0b980b8ecefb20361dc56bc2fb6edab8dd_f24a0e9e_f77d1cc1-01b0-41fc-b975-d02d7a7e6ae9
    
    Analysis symbol: 
    Rechecking for solution: 0
    Report Id: 8013b07a-2841-472a-9293-0ee4a83e2b97
    Report Status: 268435456
    Hashed bucket: aa9bafd823ce71109a5c74ff8b919b71
    Cab Guid: 0

Report.wer:

    Version=1
    EventType=APPCRASH
    EventTime=133063024517935847
    ReportType=2
    Consent=1
    UploadTime=133063024522012531
    ReportStatus=268435456
    ReportIdentifier=f77d1cc1-01b0-41fc-b975-d02d7a7e6ae9
    IntegratorReportIdentifier=8013b07a-2841-472a-9293-0ee4a83e2b97
    Wow64Host=34404
    NsAppName=remedybg.exe
    OriginalFilename=remedybg.exe
    AppSessionGuid=000068bc-0001-0098-63f4-2aa11dbcd801
    TargetAppId=W:0006ed43b4d7f17138c6ce162497ae9ead6100000904!0000162834d5bfedcda3dcc6937aff445f4736be6e4c!remedybg.exe
    TargetAppVer=2022//08//29:00:42:25!0!remedybg.exe
    BootId=4294967295
    TargetAsId=1262
    UserImpactVector=808452912
    IsFatal=1
    EtwNonCollectReason=1
    Response.BucketId=aa9bafd823ce71109a5c74ff8b919b71
    Response.BucketTable=4
    Response.LegacyBucketId=1899521783750564721
    Response.type=4
    Sig[0].Name=Application Name
    Sig[0].Value=remedybg.exe
    Sig[1].Name=Application Version
    Sig[1].Value=0.3.8.2
    Sig[2].Name=Application Timestamp
    Sig[2].Value=630c0b71
    Sig[3].Name=Fault Module Name
    Sig[3].Value=remedybg.exe
    Sig[4].Name=Fault Module Version
    Sig[4].Value=0.3.8.2
    Sig[5].Name=Fault Module Timestamp
    Sig[5].Value=630c0b71
    Sig[6].Name=Exception Code
    Sig[6].Value=c0000005
    Sig[7].Name=Exception Offset
    Sig[7].Value=00000000000965e8
    DynamicSig[1].Name=OS Version
    DynamicSig[1].Value=10.0.19044.2.0.0.256.48
    DynamicSig[2].Name=Locale ID
    DynamicSig[2].Value=4105
    DynamicSig[22].Name=Additional Information 1
    DynamicSig[22].Value=0e00
    DynamicSig[23].Name=Additional Information 2
    DynamicSig[23].Value=0e005953c59c95555eb06ac2c92f4c0c
    DynamicSig[24].Name=Additional Information 3
    DynamicSig[24].Value=8d5c
    DynamicSig[25].Name=Additional Information 4
    DynamicSig[25].Value=8d5c1811c31afeb89fc83d1eb9271c26
    UI[2]=C:\remedydbg\remedybg.exe
    LoadedModule[0]=C:\remedydbg\remedybg.exe
    LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
    LoadedModule[2]=C:\WINDOWS\System32\KERNEL32.DLL
    LoadedModule[3]=C:\WINDOWS\System32\KERNELBASE.dll
    LoadedModule[4]=C:\WINDOWS\SYSTEM32\apphelp.dll
    LoadedModule[5]=C:\WINDOWS\System32\USER32.dll
    LoadedModule[6]=C:\WINDOWS\System32\win32u.dll
    LoadedModule[7]=C:\WINDOWS\System32\GDI32.dll
    LoadedModule[8]=C:\WINDOWS\System32\gdi32full.dll
    LoadedModule[9]=C:\WINDOWS\System32\msvcp_win.dll
    LoadedModule[10]=C:\WINDOWS\System32\ucrtbase.dll
    LoadedModule[11]=C:\WINDOWS\System32\ole32.dll
    LoadedModule[12]=C:\WINDOWS\System32\RPCRT4.dll
    LoadedModule[13]=C:\WINDOWS\System32\combase.dll
    LoadedModule[14]=C:\WINDOWS\System32\bcrypt.dll
    LoadedModule[15]=C:\WINDOWS\System32\SHELL32.dll
    LoadedModule[16]=C:\WINDOWS\System32\IMM32.dll
    LoadedModule[17]=C:\WINDOWS\SYSTEM32\d3d11.dll
    LoadedModule[18]=C:\WINDOWS\System32\msvcrt.dll
    LoadedModule[19]=C:\WINDOWS\SYSTEM32\dxgi.dll
    LoadedModule[20]=C:\WINDOWS\SYSTEM32\kernel.appcore.dll
    LoadedModule[21]=C:\WINDOWS\System32\bcryptPrimitives.dll
    LoadedModule[22]=C:\WINDOWS\system32\uxtheme.dll
    LoadedModule[23]=C:\WINDOWS\SYSTEM32\windows.storage.dll
    LoadedModule[24]=C:\WINDOWS\SYSTEM32\Wldp.dll
    LoadedModule[25]=C:\WINDOWS\System32\advapi32.dll
    LoadedModule[26]=C:\WINDOWS\System32\sechost.dll
    LoadedModule[27]=C:\WINDOWS\System32\SHCORE.dll
    LoadedModule[28]=C:\WINDOWS\System32\shlwapi.dll
    LoadedModule[29]=C:\WINDOWS\SYSTEM32\profapi.dll
    LoadedModule[30]=C:\WINDOWS\System32\MSCTF.dll
    LoadedModule[31]=C:\WINDOWS\System32\OLEAUT32.dll
    LoadedModule[32]=C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_df0bee9f4cb9436e\nvldumdx.dll
    LoadedModule[33]=C:\WINDOWS\SYSTEM32\VERSION.dll
    LoadedModule[34]=C:\WINDOWS\SYSTEM32\msasn1.dll
    LoadedModule[35]=C:\WINDOWS\SYSTEM32\cryptnet.dll
    LoadedModule[36]=C:\WINDOWS\System32\CRYPT32.dll
    LoadedModule[37]=C:\WINDOWS\SYSTEM32\drvstore.dll
    LoadedModule[38]=C:\WINDOWS\SYSTEM32\devobj.dll
    LoadedModule[39]=C:\WINDOWS\System32\cfgmgr32.dll
    LoadedModule[40]=C:\WINDOWS\SYSTEM32\cryptbase.dll
    LoadedModule[41]=C:\WINDOWS\System32\WINTRUST.DLL
    LoadedModule[42]=C:\WINDOWS\System32\imagehlp.dll
    LoadedModule[43]=C:\WINDOWS\SYSTEM32\CRYPTSP.dll
    LoadedModule[44]=C:\WINDOWS\system32\rsaenh.dll
    LoadedModule[45]=C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_df0bee9f4cb9436e\nvwgf2umx.dll
    LoadedModule[46]=C:\WINDOWS\SYSTEM32\WINMM.dll
    LoadedModule[47]=C:\WINDOWS\SYSTEM32\dxcore.dll
    LoadedModule[48]=C:\WINDOWS\SYSTEM32\textinputframework.dll
    LoadedModule[49]=C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
    LoadedModule[50]=C:\WINDOWS\SYSTEM32\CoreMessaging.dll
    LoadedModule[51]=C:\WINDOWS\System32\WS2_32.dll
    LoadedModule[52]=C:\WINDOWS\SYSTEM32\ntmarta.dll
    LoadedModule[53]=C:\WINDOWS\SYSTEM32\wintypes.dll
    LoadedModule[54]=C:\WINDOWS\System32\clbcatq.dll
    LoadedModule[55]=C:\Program Files (x86)\DisplayFusion\Hooks\AppHook64_CA01091B-5857-4BCD-AB8E-26212500361F.dll
    LoadedModule[56]=C:\WINDOWS\SYSTEM32\dwmapi.dll
    LoadedModule[57]=C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll
    State[0].Key=Transport.DoneStage1
    State[0].Value=1
    OsInfo[0].Key=vermaj
    OsInfo[0].Value=10
    OsInfo[1].Key=vermin
    OsInfo[1].Value=0
    OsInfo[2].Key=verbld
    OsInfo[2].Value=19044
    OsInfo[3].Key=ubr
    OsInfo[3].Value=1949
    OsInfo[4].Key=versp
    OsInfo[4].Value=0
    OsInfo[5].Key=arch
    OsInfo[5].Value=9
    OsInfo[6].Key=lcid
    OsInfo[6].Value=1033
    OsInfo[7].Key=geoid
    OsInfo[7].Value=39
    OsInfo[8].Key=sku
    OsInfo[8].Value=48
    OsInfo[9].Key=domain
    OsInfo[9].Value=0
    OsInfo[10].Key=prodsuite
    OsInfo[10].Value=256
    OsInfo[11].Key=ntprodtype
    OsInfo[11].Value=1
    OsInfo[12].Key=platid
    OsInfo[12].Value=10
    OsInfo[13].Key=sr
    OsInfo[13].Value=0
    OsInfo[14].Key=tmsi
    OsInfo[14].Value=221768937
    OsInfo[15].Key=osinsty
    OsInfo[15].Value=3
    OsInfo[16].Key=iever
    OsInfo[16].Value=11.789.19041.0-11.0.1000
    OsInfo[17].Key=portos
    OsInfo[17].Value=0
    OsInfo[18].Key=ram
    OsInfo[18].Value=65413
    OsInfo[19].Key=svolsz
    OsInfo[19].Value=930
    OsInfo[20].Key=wimbt
    OsInfo[20].Value=0
    OsInfo[21].Key=blddt
    OsInfo[21].Value=191206
    OsInfo[22].Key=bldtm
    OsInfo[22].Value=1406
    OsInfo[23].Key=bldbrch
    OsInfo[23].Value=vb_release
    OsInfo[24].Key=bldchk
    OsInfo[24].Value=0
    OsInfo[25].Key=wpvermaj
    OsInfo[25].Value=0
    OsInfo[26].Key=wpvermin
    OsInfo[26].Value=0
    OsInfo[27].Key=wpbuildmaj
    OsInfo[27].Value=0
    OsInfo[28].Key=wpbuildmin
    OsInfo[28].Value=0
    OsInfo[29].Key=osver
    OsInfo[29].Value=10.0.19041.1949.amd64fre.vb_release.191206-1406
    OsInfo[30].Key=buildflightid
    OsInfo[30].Value=5AFFFB9B-FB87-4242-B66A-4ECEEB1CF75F.1
    OsInfo[31].Key=edition
    OsInfo[31].Value=Professional
    OsInfo[32].Key=ring
    OsInfo[32].Value=Retail
    OsInfo[33].Key=expid
    OsInfo[34].Key=fconid
    OsInfo[35].Key=containerid
    OsInfo[36].Key=containertype
    OsInfo[37].Key=edu
    OsInfo[37].Value=0
    FriendlyEventName=Stopped working
    ConsentKey=APPCRASH
    AppName=RemedyBG x64 debugger
    AppPath=C:\remedydbg\remedybg.exe
    NsPartner=windows
    NsGroup=windows8
    ApplicationIdentity=796D872B8814E2D85BCA84F534BDABF4
    MetadataHash=521009909

**Comment by x13pixels** [comment]
0.3.8.3: Fixed regression in call stack display when a symbol cannot be found for one or more of the function's parameters.
