### ISSUE TITLE
RemedyBG doesn't handle UTF-8 BOM in files

### ISSUE THREAD

**Issue by sonictk** [x13pixels/remedybg-issues#269]
If a source file has the UTF-8 BOM (`0xffbbbf`), RemedyBG displays a `?` character when the source file is opened.

![image](https://user-images.githubusercontent.com/2504199/192401604-ea58f693-e463-4293-b42d-d0925d4c7297.png)

I've uploaded a file that should reproduce the screenshot above.
[test.txt](https://github.com/x13pixels/remedybg-issues/files/9650371/test.txt)

**Comment by x13pixels** [comment]
Code existed to detect UTF-8, UTF-16 LE, and UTF-16 BE but at some point, this was broke and the initial line renders the BOM. Thanks for pointing this out.
