### ISSUE TITLE
Fix for prettier message boxes

### ISSUE THREAD

**Issue by mmozeiko** [x13pixels/remedybg-issues#270]
Don't know if this is intentional or not, but message boxes look a bit out of place with its Win95 style:

![image](https://user-images.githubusercontent.com/1665010/194142222-e7e26354-3409-42a0-ace9-62e9e30a6ab6.png)

Normal Windows applications with proper style should look like this (depending on your Windows version):

![image](https://user-images.githubusercontent.com/1665010/194142827-d948914d-729a-4292-9fc1-67d9890c9db0.png)

This is fixed by adding Common Controls v6 manifest: https://learn.microsoft.com/en-us/windows/win32/controls/cookbook-overview

So you simply add this in your .manifest file and it will look pretty:
```
<dependency>
  <dependentAssembly>
    <assemblyIdentity type="win32" name="Microsoft.Windows.Common-Controls" version="6.0.0.0" processorArchitecture="*" publicKeyToken="6595b64144ccf1df" language="*" />
  </dependentAssembly>
</dependency>
```

**Comment by x13pixels** [comment]
Thanks.
