### ISSUE TITLE
Certain text elements have low contrast in light mode

### ISSUE THREAD

**Issue by nuudlman** [x13pixels/remedybg-issues#273]
Eg: 
![изображение](https://user-images.githubusercontent.com/62861466/196339489-e5f5aae1-1c87-4510-bac8-2f3019230dd3.png)

Upon some further investigation, the contrast seems fine on my second monitor (which only covers sRGB), but on my main monitor (which covers DCI-P3), the contrast is notably worse (presumably as the yellow is stretched to a higher saturation).

**Comment by x13pixels** [comment]
Tweaked the value of the text color for light-mode to (hopefully) make it easier to see.
