### ISSUE TITLE
symbols containing periods

### ISSUE THREAD

**Issue by kaiserschmarrn0** [x13pixels/remedybg-issues#275]
DMD writes symbols containing periods to pdb files: `0000000000000008          8 SymTagData            test_module.global_var                        ?(0)`

(I think) Remedy parses these as struct fields: `Identifier "test_module" not found`

I'd like to use a backslash to escape periods.

**Comment by kaiserschmarrn0** [comment]
i have since read that both dmd and ldc may not emit working debug symbols on 64 bit windows, and that some debuggers do extra work to support d anyway.

adding this feature would probably be meaningless, so if there's no other reason to have it, i suggest you close the issue

**Comment by x13pixels** [comment]
Added an escape to support identifiers with dots in them (0.3.9.1). In the example above, this would be written as "`test_module.global_val" (prefix the identifier with a backtick).
