### ISSUE TITLE
Feature Request: show MXCSR in register panel

### ISSUE THREAD

**Issue by Kaloffl** [x13pixels/remedybg-issues#278]
Hello, 
I'm currently debugging a problem with incorrectly rounded float values and it would be really helpful to see the bits of the MXCSR register in order to see the rounding mode, underflow flag, etc. As far as I can tell, this register is missing from the register tab and can't be added, as of 0.3.8.4. 
Nevertheless many thanks for this great tool!

**Comment by x13pixels** [comment]
0.3.8.6 added decomposed bits of MXCSR to register panel; add support for mxcsr register in watch expressions
