### ISSUE TITLE
Crash when reloading module with conditional breakpoint

### ISSUE THREAD

**Issue by Kipt** [x13pixels/remedybg-issues#282]
RemedyBG: 0.3.8.7

I consistently get crashes (100% repro rate) when setting a conditional breakpoint inside a DLL file, then offloading and reloading a new DLL with the same name as the previous one. This does not happen with normal breakpoints. I haven't created a minimum repro case for this but as I get it consistently I presume it's easy to figure one out.

Steps to reproduce:
1. Create a program that loads a DLL using `LoadLibrary`.
2. Set a conditional breakpoint anywhere inside the DLL.
3. Offload the DLL using `FreeLibrary`.
4. Load a new library with same name using `LoadLibrary`

Expected behavior:
- Previous breakpoint should work.

Actual behavior:
- RemebyBG crashes.

**Comment by x13pixels** [comment]
Fixed in 0.3.8.8
