### ISSUE TITLE
Disassembly window does not always function

### ISSUE THREAD

**Issue by kcbanner** [x13pixels/remedybg-issues#284]
Version 0.3.8.8

I've noticed this specifically when debugging the `zig` compiler, but the disassembly window doesn't populate:

![image](https://user-images.githubusercontent.com/74892/233799960-df5dfcbb-ad6e-4f84-a178-23c0dd72f89b.png)

I think it might be related to the program being debugged spawning sub-processes.

I can provide any extra additional information to help diagnose.

**Comment by x13pixels** [comment]
Possibly related to #234

**Comment by x13pixels** [comment]
Fixed for next release.

zig.exe's 176 MiB .text section was larger than an upper limit of 32 MiB enforced when analyzing the section prior to disassembly. Optimized the analysis and removed this limit.

**Comment by kcbanner** [comment]
Thanks!
