### ISSUE TITLE
Possible to specify a command relative to the project directory?

### ISSUE THREAD

**Issue by scallyw4g** [x13pixels/remedybg-issues#285]
I've been using Remedy for a year or two now on a personal project, and it's really great.

My personal project has started to gather some interest from potential contributors, and I'd like to provide
those contributors licenses for Remedy, but there's one (at least I think) inconveniently missing feature
I'd like to ask about.

Is it possible to specify a target command (and working dir) relative to the path of the current .rdbg project
file?  I've played around with a number of configurations (moving the remedy exe, trying different paths, slashes, etc)
and can't get it to work with a relative path.

The reason I want this is because (obviously) everyone keeps their work folders in a different place,
and I'd like to avoid the setup instructions for contributors to involve "change these 10 paths in the debugger manually",
if possible.

Just to be 100% clear, I have this:

<img width="550" alt="Screenshot 2023-06-10 112158" src="https://github.com/x13pixels/remedybg-issues/assets/6423361/13e82323-931d-4d26-9b8a-c8b5175fc4d6">

And would prefer this:

<img width="543" alt="Screenshot 2023-06-10 112331" src="https://github.com/x13pixels/remedybg-issues/assets/6423361/afdf068b-e6eb-4115-9d5e-620815675a30">

Anywhoo, hopefully I'm just dense and this is already a thing, but if it's not I guess this is a humble feature request :)

Thanks for all your hard work on Remedy, it's great!!

**Comment by x13pixels** [comment]
Implemented in 0.4.0.4: command and working directory will now be based on the RDBG directory when necessary.

**Comment by scallyw4g** [comment]
Just downloaded 0.4.0.4 .. confirmed it's working for me.  Thank you so much for implementing this George!!!! <3
