### ISSUE TITLE
Executable not found forever

### ISSUE THREAD

**Issue by seventh-chord** [x13pixels/remedybg-issues#286]
Using version 0.3.9.0.

If I type some garbage into the command field and try to launch, I get this error:

![image](https://github.com/x13pixels/remedybg-issues/assets/16702339/75f40430-f86e-4e0f-920a-01062749c4ec)

But each time I hit "Ok" or press escape the dialog box disappears and a new, identical one reappears. I have to kill remedy from the task manager and start it up again to get back to work.

Happens both when creating a new session and when opening an existing session and starting debugging immediately.

**Comment by 4lex1v** [comment]
Same thing with working directory, I'd think the source of the issue is the same, just reporting fyi
![image](https://github.com/x13pixels/remedybg-issues/assets/1001122/86c8b208-0b6e-4e09-a4eb-09f84250051e)

**Comment by x13pixels** [comment]
Fixed for 0.3.9.1
