### ISSUE TITLE
Remedybg softlocks when attempting to debug non executables with keyboard shortcuts.

### ISSUE THREAD

**Issue by purple-blog** [x13pixels/remedybg-issues#288]
# Steps to reproduce
1. Supply remedybg a path to a non executable file for the `Command` field in the session tab.
2. Start a debugging session using any of the debugger initialization shortcuts.
3. Remedybg will then prompt a message box with the following error message: `Unable to debug process: unknown reason`
4. Confirming the prompt with OK or with the enter key will continuously reopen the previously mentioned message box with the same error message. The only way to stop this was by killing the application process in a task manager.

# Other notes
This bug can commonly occur when supplying remedybg with the wrong file path when initializing from the command line. 
Example: `remedybg.exe main.c` instead of `remedybg.exe main.exe`

This bug does **not** occur when initializing a debugging session from the `Control` menu.

**Comment by x13pixels** [comment]
Fixed in 0.3.9.1
