### ISSUE TITLE
feature: add ability to display slices

### ISSUE THREAD

**Issue by ryuukk** [x13pixels/remedybg-issues#289]
If the type has a length and a ptr, it should be able to be displayed like an array, so it's easier to debug

Perhaps a menu ``Display as -> Array`` then input to say wich field is length, wich is pointer

Or perhaps something that detects that automatically

Example:

```D
    State[32] states1;
    State[] states2 = states1[0 .. 4];
```

![image](https://github.com/x13pixels/remedybg-issues/assets/44361234/6487b02b-6a7c-4b31-a46a-5c920c509ead)

**Comment by chrisbriend** [comment]
if I understand this correctly, you can already do that in the watch window. see num elements format specifier in the doc:
 -- <num elements>: This is for specifying the number of elements to display in an array or pointer
   type. The value can be an integer literal or an integer/enum value that can be resolved in the
   current scope. The <num elements> expression can be used in conjunction with another format
   specifier.

       arr, 16            # Display 16 values of the expression 'arr'. 
       arr, count         # Display 'count' values of the expression 'arr'. 
       arr, X count       # Display 'count' values of the expression 'arr' in upper-case hexadecimal
       
if you wanted this to be done automatically though, then that is another story..
(Note that the msvc debugger also already provide support for the arr, 16 format.)

**Comment by x13pixels** [comment]
Implementing natvis, or something similar, is on the roadmap and will cover this case. In the meantime, chrisbriend's suggestions will work, though do not automatically apply to a type. Thanks @ryuukk!
