### ISSUE TITLE
Broken for inline static variable

### ISSUE THREAD

**Issue by GloriousPtr** [x13pixels/remedybg-issues#290]
~Watch window can't find inline static variable.~
Hovering on static variable doesn't work.

Declaration: `inline static Renderer3DData* s_Data;`

![inline_static_variable](https://github.com/x13pixels/remedybg-issues/assets/29519295/58714aa8-ed42-4b0f-9fbc-826eab587906)

Edit1: Watch window displays it correctly with proper namespace. Hovering doesn't work though.

**Comment by x13pixels** [comment]
This behavior appears to be a bug in Clang. Will probably need to add a work around for this as it still isn't fixed. Closing as a duplicate as this is captured in #213. In any case, I appreciate the report!
