### ISSUE TITLE
When launched as JIT debugger it needs two times ALT+F4 in order to close

### ISSUE THREAD

**Issue by akowalew** [x13pixels/remedybg-issues#291]
Hi! 

When trying to use RemedyBG as JIT debugger I observed that I have to hit twice ALT+F4 in order to close the debugger. First time I hit ALT+F4 it looks like the debugger has been closed but right after that immediately reopened. From the other side when I just click menu Session->Exit then it quits properly immediately. It is not critical, but makes some confusion. :)

Registry settings:
![image](https://github.com/x13pixels/remedybg-issues/assets/11333571/e4b7dc7a-efab-406a-8a51-c422a087b837)

Created simple program for segfault:

```
int main(int argc, char const *argv[])
{
    *(int*)(0) = 0;
    return 0;
}
```

Compiling and launching:

```
cl main.c
main.exe
```

Hope that helps reproducing the problem.
Best regards
Adam

**Comment by x13pixels** [comment]
Thanks for the info @akowalew. This will be fixed in the next release.

[0.3.9.5] Fixed a case in which detaching from a target at program shutdown would cause the jit debugger to launch a second instance of RemedyBG.
