### ISSUE TITLE
Remedy fails to kill process

### ISSUE THREAD

**Issue by Jens-GameLoom** [x13pixels/remedybg-issues#292]
Somewhat randomly RemedyBG 0.3.9.4 fails to stop the debugging process, roughly once every 3 hours or so.

The UI remains responsive but trying to break, restart or stop debugging does nothing. Status title (the colored part on the top) says `Program is running because Control|Continue was clicked`.

Checking the task manager I see the process under 'RemedyBG x64 debugger' group, but trying to kill the debugged process through task manager does nothing.

When closing RemedyBG in this state the debugged process transfers to background processes. The exe file cannot be stopped using the task manager, nor deleted as it is still running. The only way I've find to solve this problem is to reboot the computer.

I have not seen this behavior in earlier versions (last version I used on this computer was 0.3.9.0).

**Comment by Jens-GameLoom** [comment]
Actually I just reproduced this with 0.3.9.0 as well.

**Comment by x13pixels** [comment]
This should be fixed in 0.3.9.5 (next, upcoming release).
