### ISSUE TITLE
QoL feature request: don’t stop process when attaching to it

### ISSUE THREAD

**Issue by JustSlavic** [x13pixels/remedybg-issues#293]
When RemedyBG is attached to a process, it stops the process at the point where it is executing at the moment.
This is quite an inconvenient to me, because it opens up new tab with the code each time I attach to a process. And since the project is big enough, the tabs never repeat with each attach, so it’s hard to navigate through them.

I suggest that Remedy would not stop process right away and continued as normal, but stopped it only if hit the breakpoint.
Thanks.

**Comment by x13pixels** [comment]
No longer halt execution when attaching to a process.

Fix to ship in 0.3.9.7
