### ISSUE TITLE
Run-away stepping in newer builds of RemedyBG

### ISSUE THREAD

**Issue by cmuratori** [x13pixels/remedybg-issues#294]
In (at least) the latest version of RemedyBG (3.9.6), RemedyBG appears to get into a stuck-key (or stuck command?) situation where it continuously steps through the executable even though no keys are depressed. I use RemedyBG extensively, and daily, so I am very certain this bug was introduced sometime in the last few versions or so, probably in the 3.9 series (I was previously using the 3.8 series).

I am not sure how to reproduce this issue, since it only happens once every 10 or so times I launch an executable. But I believe the best chance of reproducing is to try to start debugging an executable by hitting F10 or F11, expecting to stop on the first line on the program. Most of the time, this works correctly, but every so often, it appears that the command is "stuck" and Remedy repeatedly steps through the code.

Strangely, there does not appear to be any way to stop it. Hitting the F10/F11 keys to try to "reset" the state does not seem to work.

\- Casey

**Comment by x13pixels** [comment]
Thanks. This was likely introduced after upgrading to a later Dear ImGui in 0.3.9.0 which introduced a different approach to buffering keyboard input. RemedyBG is likely mishandling something w.r.t. this change.

**Comment by cmuratori** [comment]
I thought that might be the case, but since I've never used Dear ImGui, I wasn't sure if it handled the keyboard or not! But that does seem like a very likely culprit if so...

\- Casey

**Comment by x13pixels** [comment]
Tracked to https://github.com/ocornut/imgui/blob/master/imgui.cpp#L9142

Keyboard state is cleared in ImGui::UpdateInputEvents whenever the application loses focus (io.AppFocusLost). This was ostensibly written to handle the case when a key up event is not sent to the window and prevents "stuck" keys.

However, when two or more focus change events are processed in the event queue in the same frame, with the last event being "focused", the current implementation will set io.AppFocusLost to false, preventing the key state from being cleared.

Changed the implementation to set io.AppFocusLost only when focus is lost, and not for every focus change event, noting that io.AppFocusLost is already reset to false in ImGui::EndFrame.

Fix to ship in 0.3.9.7.
