### ISSUE TITLE
Expand/collapse buggy in 0.3.9

### ISSUE THREAD

**Issue by cmuratori** [x13pixels/remedybg-issues#295]
Since upgrading to the 0.3.9 branch, I have found that expand/collapse in the watch window is unreliable. Although I do not have a way to reproduce it consistently, I find that when I have multiple items expanded in an array, and I try to collapse or expand a single one of them, others randomly expand and collapse as well. I do not recall experiencing this in any prior version, so it may be another Dear ImGui upgrade issue?

\- Casey

**Comment by x13pixels** [comment]
Tracked this down to a less-than-robust check for type equivalence across runs of RemedyBG. The idea was to preserve the fold state across runs but this can fail, as described above, in the case that a structure's declaration changes with the type id remaining the same in the symbol file. Disabled the "across run" preservation of fold state for now.

Fix to ship in 0.3.9.7.
