### ISSUE TITLE
Source view scroll bar loses focus during scrolling in 0.3.9

### ISSUE THREAD

**Issue by cmuratori** [x13pixels/remedybg-issues#296]
Since upgrading to the 0.3.9 branch, the scroll bar for the main source view no longer properly keeps focus while actively scrolling. To reproduce, place the watch window to the right of the source window. Click-and-drag the source window scroll bar, and while scrolling, allow the mouse cursor to move off the scroll bar slightly so that it moves over the watch window. Assuming it behaves as it does on my machine, the scroll action will stop abruptly, and the watch window will highlight, as if it you had released the mouse button then left-clicked.

As with my other recent reports, I do not recall experiencing this in any prior version, so it may be another Dear ImGui upgrade issue.

\- Casey

**Comment by x13pixels** [comment]
Dear ImGui introduced a change in behavior here: https://github.com/ocornut/imgui/commit/b15347cb7d0fb3ba9a98420d17ea056e8415e63f which required a work-around in RemedyBG. Thanks for reporting this.

Fix to ship in 0.3.9.7.
