### ISSUE TITLE
Watch window shows wrong value when multiplying bitfield member.

### ISSUE THREAD

**Issue by PascalBeyer** [x13pixels/remedybg-issues#301]
In the following program:
```c
typedef unsigned char    u8;

struct unwind_code{
    u8 offset_in_prolog;
    u8 operation_code : 4;
    u8 operation_info : 4;
};

int main(){    
    struct unwind_code unwind_code = {
        .offset_in_prolog = 0xa,
        .operation_code = 0x2,
        .operation_info = 0xe,
    };       
    __debugbreak();    
    return 0;
} 
```
I get the following values:
![image](https://github.com/x13pixels/remedybg-issues/assets/40343897/307933d3-a9d3-445b-a926-ecad127c678f)

For reference, The file was compiled using `cl /Z7 test.c` with version `19.29.30147` and Remedybg is version `0.3.9.9`.

Compiled files:  [repro.zip](https://github.com/x13pixels/remedybg-issues/files/14417545/repro.zip)

**Comment by x13pixels** [comment]
Fixed in next release, 0.4.0.0
