### ISSUE TITLE
Trying to display std::string sometimes lead to "unable to read process memory"

### ISSUE THREAD

**Issue by neeraj9** [x13pixels/remedybg-issues#302]
- RemedyBG version 0.3.9.9
- Windows 11, 23H2 (OS Build 22631.3296
- Running RemedyBG as regular user
- Sample code in C++

In general RemedyBG works amazingly good, but sometimes I notice that it cannot access process memory. I am running remedybg as a regular user on Windows 11.

The following example demonstrates me trying to display
a `std::string` variable `url_`. Any pointers to understand this better will be helpful.

```
*url_._Mypair._Myval2._Bx._Ptr;??? (unable to read process memory);char;
```

**Comment by x13pixels** [comment]
Looks like if the std::string's `test._Mypair._Myval2._Myres` is less than 16 then the expression should be `url_._Mypair._Myval2._Bx._Buf` instead of `url_._Mypair._Myval2._Bx._Ptr`. Closing this a duplicate as it will be rolled in as part of the natvis / custom watch work.

Thank you!
