### ISSUE TITLE
RemedyBG v0.3.9.9 crashes when pdb file is 4GB+

### ISSUE THREAD

**Issue by neeraj9** [x13pixels/remedybg-issues#303]
RemedyBG Version: 0.3.9.9
Operating System: Windows 11

RemedyBG crashes when one of the shared library (DLL) has pdb > 4GB.

**Comment by yahuaru** [comment]
Having the same issue.
I have tested versions from 0.3.8.8 to 0.4.0.2, all having the same crash.
Sometimes program crashes with error popup "The instruction at 0x00007FF614854D1D referenced memory at 0x0000000000000000. The memory could not be read."

**Comment by bluespeck** [comment]
I'm using 0.4.0.2 and I think I have the same crash, but I don't know for sure. Opening the dump file I got the following:

RAX = 0000000000000000 RBX = 0000000040403240 RCX = 000000E4969FE828 RDX = 0000000000000000 RSI = 0000000000000000 RDI = 0000000040403240 R8  = 0000026200800040 R9  = 0000000040403240 R10 = 0000000000000000 R11 = 0000000000000246 R12 = 0000026200800040 R13 = 0000000000000AF4 R14 = 00000000000E8D30 R15 = 000000E4969FE7F0 RIP = 00007FF685187760 RSP = 000000E4969FE6A0 RBP = 0000000000002000 EFL = 00010202 

0x00000000000E8D30 = 00000000 

Unhandled exception at 0x00007FF685187760 (remedybg.exe) in remedybg.exe.28080.dmp: 0xC0000005: Access violation reading location 0x00000000000E8D30.
With this callstack:
	remedybg.exe!00007ff685187760()
 	remedybg.exe!00007ff68519404c()
 	remedybg.exe!00007ff6851847ee()
 	remedybg.exe!00007ff685185880()
 	remedybg.exe!00007ff6851761c1()
 	kernel32.dll!BaseThreadInitThunk()	
 	ntdll.dll!RtlUserThreadStart()

**Comment by x13pixels** [comment]
Thanks for the additional information, all.

**Comment by x13pixels** [comment]
Fixed in 0.4.0.4. Fixed computation of file positions that were using 32-bit integers.
