### ISSUE TITLE
RemedyBG v0.4.0.0: "Find Next" no longer works for files encoded in UTF-8 with BOM

### ISSUE THREAD

**Issue by sdwe** [x13pixels/remedybg-issues#304]
When a match is found (Ctrl+F) searching again (Ctrl+F) or executing "Find Next" (F3) do not proceed to the next match.
"Find Prev" (Shift+F3) works fine.

**Comment by x13pixels** [comment]
Thanks for the report. I'm not seeing this behavior in either the text or disassembly windows. Is there a specific search pattern that could be problematic?

**Comment by sdwe** [comment]
Thanks for your feedback!
I have examined the situation more closely.
The problem occurs with files with UTF-8 encoding and BOM.
(For technical reasons, all our source files have a BOM.)
The search pattern does not seem to play a role.

Example: Search "diam" in [lorem.txt](https://github.com/x13pixels/remedybg-issues/files/15042070/lorem.txt).

**Comment by x13pixels** [comment]
Exactly the detail I needed to know. Thanks much!

Fixed for next release 0.4.0.1.

**Comment by sdwe** [comment]
A big thank you!
