### ISSUE TITLE
Text selection / freeze bug

### ISSUE THREAD

**Issue by hweickert** [x13pixels/remedybg-issues#311]
Hello, Hello,

I noticed a bug in the latest version which, fairly consistently, leads to a freeze/crash:

1. Have the console auto clear feature turned on.
2. Start a debugging session & end it
4. Select text in the console window (greatly appreciated feature btw.!!!!) to copy/paste elsewhere
4. Start another debugging session
5. End my program
6. (At this point the text seems to be marked/selected again btw.) Try to select text again
7. Freeze

Thank you so much for this awesome tool !!!! 👍 👍 👍

**Comment by x13pixels** [comment]
This will be fixed in the next release, 0.4.0.7.

Appreciate the writeup and my apologies for the mistake.
