### ISSUE TITLE
Attach to existing process

### ISSUE THREAD

**Issue by x13pixels** [x13pixels/remedybg-issues#45]
[forestthewoods] Is there no way to attach RemedyBG to an existing process? This is strictly required by my workflow. :(

**Comment by x13pixels** [comment]
[McMassiveNZ] The current project i'm working on actually runs two separate executables and the communicate with each other via network sockets. 

Visual studio has a feature called child process debugging which lets you automatically attach to one or more processes running. 

See image of Visual Studio extension at link: https://pasteboard.co/IbC8Fan.png

**Comment by forrestthewoods** [comment]
Use Case 1) Similar to McMassiveNZ. I have a C++ server application. Then I have a C++ DLL which is loaded by Unity3D to communicate over sockets with that server.

Use Case 2) Application crashes without debugger. Windows asks if I'd like to attach a debugger. I say yes.

**Comment by x13pixels** [comment]
Added ability to attach to a running process.

**Comment by squarewave** [comment]
The "Attach to Process..." list seems to be missing some entries. I'm trying to debug a local build of Firefox with this and all of the firefox.exe processes associated with the local build are not showing up. However, the normal firefox.exe processes from the release build are showing up.

**Comment by x13pixels** [comment]
@squarewave Are your Firefox builds targeting x86 rather than x64? RemedyBG does not show 32-bit processes in the attach UI.

**Comment by squarewave** [comment]
> @squarewave Are your Firefox builds targeting x86 rather than x64? RemedyBG does not show 32-bit processes in the attach UI.

Sorry for the delay, I've been away from my Windows dev setup and thought I may have left it on a 32-bit build, but no, it's 64-bit (according to my config and double-checked by dumpbin). Any other thoughts / things I can dump here to help debug?
