### ISSUE TITLE
String visualization

### ISSUE THREAD

**Issue by x13pixels** [x13pixels/remedybg-issues#59]
Add string visualization feature to watch window (magnifying glass to open string viewer).

**Comment by x13pixels** [comment]
[simon] I use the memory panel as a string viewer (until there is a proper one), it would be great to be able to configure the memory window to only show the ascii part without the address and value column.

**Comment by x13pixels** [comment]
Casey suggested [HH525/83 minutes] that it would be better for the string display to be inline with the watch window rather than a separate, modal dialog. In general, think about how something like this could be used for inline display of various visualizations (e.g., image display).

**Comment by sonictk** [comment]
Just to check; was this feature removed in newer releases of RemedyBG? I'm currently running 0.3.5.3 and it seems like the magnifying glass doesn't show up for C-strings anymore; only way I can view the full string is by sending it to the memory window or manually adding it as a watch and then specifying `str` on it, which gets a little annoying when dealing with lots of strings at once in the same stack frame:
![image](https://user-images.githubusercontent.com/2504199/123226426-81028980-d488-11eb-81a2-7d4c97f9b055.png)

**Comment by x13pixels** [comment]
Remedy implements an inline string preview using the ", str" formatter. There isn't a magnifying glass (like VS) that opens a modal dialog. There will be some UI enhancements to this feature in an upcoming release. Hope that helps!
