### ISSUE TITLE
Add exception settings dialog

### ISSUE THREAD

**Issue by x13pixels** [x13pixels/remedybg-issues#81]
Allow picking which exceptions the debugger will break on when thrown (first-chance).

In VS, the default Win32 exceptions that are enabled are:
0x40010005 Control-C
0x40010008 Control-Break
0xc0000005 Access violation
0xc0000008 An invalid handle was specified
0xc0000420 Assertion failed

**Comment by SimpsonGSD** [comment]
Is there any way to disable particular exceptions at all?

**Comment by x13pixels** [comment]
This was implemented in 0.4.0.2.
