### ISSUE TITLE
Open in default editor

### ISSUE THREAD

**Issue by joelvaneenwyk** [x13pixels/remedybg-issues#91]
Add option to open the current file being debugged in the default editor and/or add option to copy current filename to clipboard.

**Comment by x13pixels** [comment]
(0.2.2.0) Added option to copy filename to clipboard (right-click on tab). Opening file might require additional parameters to the text editor so will leave leave that part for another task (e.g., for Vim you'd want to pass "gvim --remote-silent '+cal cursor(line,col)' filename" or similar.
