### ISSUE TITLE
Separate Status Bar

### ISSUE THREAD

**Issue by direbroom** [x13pixels/remedybg-issues#92]
I'd love to see a status bar at the bottom with the information that's currently in the menu bar next to the menu. The "status color" and the status messages. (I don't know ImGui well enough but maybe users can grab and place that bar where they want, so someone who prefers to have it next to/in the menu bar can still have it there?)

**Comment by x13pixels** [comment]
Perhaps a right-click context menu with options to place the status bar at the top (next to the menu) or the bottom.

**Comment by x13pixels** [comment]
[92] The status text can now be displayed either on the top of the UI or
the bottom. Option in Window|Style menu as well as right-click context
menu to "Move to Top" or "Move to Bottom".
